import { useEffect, useState } from 'react';
import { Copy, Trash2, Braces, ArrowRight, Settings2, Plus, X } from 'lucide-react';
import { nodePorts } from '../lib/graph';
import { record, type Graph, type NodeDefinition, type Pipeline } from '../lib/types';
import PortEditor, { JsonField } from './PortEditor';
import { NodeIcon, nodeMeta } from './ui';

function TextField({ label, value, onSave, hint, multiline = false, optional = false }: { label: string; value: string; onSave: (value: string) => void; hint?: string; multiline?: boolean; optional?: boolean }) {
  const [error, setError] = useState('');
  const props = { 'aria-label': label, defaultValue: value, onBlur: (event: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => { if (!optional && !event.target.value.trim()) { setError('This field cannot be empty.'); return; } setError(''); if (event.target.value !== value) onSave(event.target.value); } };
  return <label className="field">{label}{multiline ? <textarea key={value} rows={5} {...props} /> : <input key={value} {...props} />}{hint ? <small>{hint}</small> : null}{error ? <span className="form-error" role="alert">{error}</span> : null}</label>;
}
function NumberField({ label, value, max, onSave, hint }: { label: string; value: number; max: number; onSave: (value: number) => void; hint: string }) {
  const [error, setError] = useState('');
  return <label className="field">{label}<input key={String(value)} type="number" aria-label={label} min={1} max={max} step={1} defaultValue={value} onBlur={event => { const n = Number(event.target.value); if (!Number.isInteger(n) || n < 1 || n > max) { setError(`Enter a whole number from 1 to ${max}.`); return; } setError(''); if (n !== value) onSave(n); }} /><small>{hint}</small>{error ? <span className="form-error" role="alert">{error}</span> : null}</label>;
}
export default function Inspector({ id, node, graph, resources, files, onEdit, onSource, onDuplicate, onRemove, onBody, importedGraphs, onWorkflow, showPorts }: {
  id?: string; node?: NodeDefinition; graph: Graph; resources: Pipeline['spec']; files: string[]; importedGraphs?: Map<string, Graph>;
  onEdit: (key: string, value: unknown) => void; onSource: () => void; onDuplicate: () => void; onRemove: () => void; onBody: () => void;
  onWorkflow?: () => void; showPorts?: boolean; onNotify?: (message: string) => void;
}) {
  const [tab, setTab] = useState<'setup' | 'ports'>('setup');
  useEffect(() => { if (showPorts) setTab('ports'); }, [showPorts]);
  if (!node || !id) return null;
  const meta = nodeMeta[node.type]; const config = record(node[node.type]); const prompt = record(config.prompt); const outputs = nodePorts(node, importedGraphs);
  const editConfig = (key: string, value: unknown) => onEdit(node.type, { ...config, [key]: value });
  const aliases = (kind: 'models' | 'mcp' | 'sandboxes') => Object.keys(resources[kind] ?? {});
  const resourceSelect = (label: string, kind: 'models' | 'mcp' | 'sandboxes', value: string, onSave: (value: string) => void) => <div className="resource-field"><label className="field">{label}<select aria-label={label} value={value} onChange={event => onSave(event.target.value)}>{!aliases(kind).includes(value) ? <option value={value}>{value || 'Choose an alias'}</option> : null}{aliases(kind).map(alias => <option key={alias}>{alias}</option>)}</select><small>Uses a resource declared in this workflow.</small></label><button className="text-button" type="button" onClick={onWorkflow}>Manage {kind}<ArrowRight size={12} /></button></div>;
  return <aside className="inspector setup-inspector"><header className="inspector-header"><span className="eyebrow">BLOCK SETTINGS</span><div className="inline"><button className="icon-button" onClick={onDuplicate} aria-label="Duplicate node"><Copy size={15} /></button><button className="icon-button" onClick={onRemove} disabled={Object.keys(graph.nodes).length <= 1} title={Object.keys(graph.nodes).length <= 1 ? 'Keep at least one block in the workflow' : 'Delete block'} aria-label="Delete node"><Trash2 size={15} /></button></div></header>
    <div className="inspector-title"><span className={`node-icon tint-${meta.color}`}><NodeIcon kind={node.type} size={20} /></span><div><h2>{id.replace(/_/g, ' ')}</h2><p>{meta.detail}</p></div></div>
    <div className="inspector-tabs"><button className={tab === 'setup' ? 'active' : ''} onClick={() => setTab('setup')}><Settings2 size={13} />Setup</button><button className={tab === 'ports' ? 'active' : ''} onClick={() => setTab('ports')}>Inputs & outputs</button></div>
    <div className="inspector-content">{tab === 'setup' ? <>
      <TextField label="Description" value={node.description ?? ''} optional onSave={value => onEdit('description', value || undefined)} />
      {['llm', 'agent'].includes(node.type) ? resourceSelect('Model alias', 'models', String(config.model ?? ''), value => editConfig('model', value)) : null}
      {['agent', 'code'].includes(node.type) ? resourceSelect('Sandbox', 'sandboxes', node.sandbox ?? '', value => onEdit('sandbox', value)) : null}
      {['llm', 'agent', 'human'].includes(node.type) ? <>
        <label className="field">Prompt source<select value={prompt.file ? 'file' : 'text'} onChange={event => { if (event.target.value === 'text') editConfig('prompt', { text: 'Describe the task to complete.' }); else { const file = files.find(file => !/\.ya?ml$/.test(file)); if (file) editConfig('prompt', { file }); } }}><option value="text">Write instructions here</option><option value="file" disabled={!files.some(file => !/\.ya?ml$/.test(file))}>Package file</option></select></label>
        {prompt.file ? <label className="field">Prompt file<select value={String(prompt.file)} onChange={event => editConfig('prompt', { file: event.target.value })}>{files.map(file => <option key={file}>{file}</option>)}</select></label> : <TextField label={node.type === 'human' ? 'Review request' : 'Instructions'} multiline value={String(prompt.text ?? '')} onSave={text => editConfig('prompt', { text })} hint="Inputs arrive as separate data. Describe the task without embedding connection syntax." />}
      </> : null}
      {node.type === 'agent' ? <><NumberField label="Maximum model steps" value={Number(config.maxSteps)} max={10000} onSave={value => editConfig('maxSteps', value)} hint="Limits how many model calls this agent can make." /><details className="field-details"><summary>Tool permissions</summary><JsonField label="Allowed tools" value={node.tools ?? { inherit: true }} validate={value => !!value && typeof value === 'object' && !Array.isArray(value)} onSave={value => onEdit('tools', value)} hint="inherit, mcp aliases with tool lists, and sandbox tool names. These are grants checked by the engine." /></details></> : null}
      {node.type === 'code' ? <div className="command-editor"><TextField label="Executable" value={String((config.command as string[])[0])} onSave={value => editConfig('command', [value, ...(config.command as string[]).slice(1)])} hint="The engine runs this executable in the selected sandbox." /><h3>Arguments</h3>{(config.command as string[]).slice(1).map((argument, index) => <div className="command-argument" key={index}><TextField label={`Argument ${index + 1}`} value={argument} optional multiline={argument.includes('\n') || argument.length > 80} onSave={value => editConfig('command', (config.command as string[]).map((arg, i) => i === index + 1 ? value : arg))} /><button className="icon-button" aria-label={`Remove argument ${index + 1}`} onClick={() => editConfig('command', (config.command as string[]).filter((_, i) => i !== index + 1))}><X size={13} /></button></div>)}<button className="text-button" onClick={() => editConfig('command', [...config.command as string[], ''])}><Plus size={13} />Add argument</button></div> : null}
      {node.type === 'tool' ? <>
        {resourceSelect('MCP server alias', 'mcp', String(config.server), value => editConfig('server', value))}
        <TextField label="Tool name" value={String(config.name)} onSave={value => editConfig('name', value)} hint="Exact tool name exposed by this MCP server." />
        <label className="field">Tool arguments<select value={'expr' in record(config.arguments) ? 'expr' : 'value'} onChange={event => editConfig('arguments', event.target.value === 'expr' ? { expr: 'args' } : { value: {} })}><option value="value">Fixed JSON object</option><option value="expr">Use block inputs (CEL)</option></select></label>
        {'expr' in record(config.arguments) ? <TextField label="Arguments expression" value={String(record(config.arguments).expr)} onSave={expr => editConfig('arguments', { expr })} hint={'args contains this block’s inputs; return an object, e.g. {"query": args.topic}.'} /> : <JsonField label="Arguments JSON" value={record(config.arguments).value ?? config.arguments} onSave={value => editConfig('arguments', { value })} validate={value => !!value && typeof value === 'object' && !Array.isArray(value)} hint="A JSON object with the tool’s argument names." />}
        <label className="field">Response format<select value={String(config.response ?? 'structured')} onChange={event => editConfig('response', event.target.value)}><option value="structured">Structured data</option><option value="content">Content blocks</option></select></label>
      </> : null}
      {node.type === 'switch' ? <>
        <p className="setup-hint">First matching condition wins. Later blocks can read the route output in their run condition.</p>
        {(config.cases as { name: string; when: string }[]).map((item, index) => <div className="setup-group" key={index}><TextField label={`Route ${index + 1} name`} value={item.name} onSave={name => editConfig('cases', (config.cases as any[]).map((item, i) => i === index ? { ...item, name } : item))} /><TextField label={`Route ${index + 1} condition`} value={item.when} onSave={when => editConfig('cases', (config.cases as any[]).map((item, i) => i === index ? { ...item, when } : item))} hint="A CEL boolean using args, e.g. args.score > 0.8." /><button className="text-button" disabled={(config.cases as any[]).length <= 1} onClick={() => editConfig('cases', (config.cases as any[]).filter((_, i) => i !== index))}>Remove route</button></div>)}
        <button className="text-button" onClick={() => { const cases = config.cases as { name: string; when: string }[]; let i = cases.length + 1; while (cases.some(item => item.name === `route_${i}`) || config.default === `route_${i}`) i++; editConfig('cases', [...cases, { name: `route_${i}`, when: 'false' }]); }}><Plus size={13} />Add route</button>
        <TextField label="Default route" value={String(config.default)} onSave={value => editConfig('default', value)} />
      </> : null}
      {node.type === 'foreach' ? <><label className="field">Collection input<select value={String(config.over)} onChange={event => editConfig('over', event.target.value)}>{Object.entries(node.inputs ?? {}).filter(([, port]) => record(port.schema).type === 'array' || port.artifact?.collection).map(([name]) => <option key={name}>{name}</option>)}</select></label><NumberField label="Concurrent iterations" value={Number(config.concurrency)} max={2147483647} onSave={value => editConfig('concurrency', value)} hint="How many items may be processed at once." /></> : null}
      {node.type === 'loop' ? <><NumberField label="Maximum iterations" value={Number(config.maxIterations)} max={100000} onSave={value => editConfig('maxIterations', value)} hint="A hard limit on repeated body execution." /><TextField label="Stop condition" value={String(config.until)} onSave={value => editConfig('until', value)} hint="A CEL boolean evaluated after the body finishes." /><label className="field">When the limit is reached<select value={String(config.onLimit)} onChange={event => editConfig('onLimit', event.target.value)}><option value="fail">Fail the run</option><option value="return_last">Return the last result</option></select></label><details className="field-details"><summary>State carried between iterations</summary><JsonField label="Loop state" value={config.state} onSave={value => editConfig('state', value)} validate={value => !!value && typeof value === 'object' && !Array.isArray(value)} hint="Each state value declares schema, initial binding and next binding." /></details></> : null}
      {['foreach', 'loop'].includes(node.type) ? <><button className="button full" onClick={onBody}>Edit body graph<ArrowRight size={15} /></button><details className="field-details"><summary>Inputs passed to the body</summary><JsonField label="Body input bindings" value={config.with} onSave={value => editConfig('with', value)} validate={value => !!value && typeof value === 'object' && !Array.isArray(value)} hint={node.type === 'foreach' ? 'Bind body input names to args, iteration.item or iteration.index.' : 'Bind body input names to args, state or iteration.index.'} /></details></> : null}
      {node.type === 'pipeline' ? <><label className="field">Child pipeline file<select aria-label="Child pipeline file" value={String(config.file)} onChange={event => editConfig('file', event.target.value)}>{files.filter(file => /\.ya?ml$/.test(file)).map(file => <option key={file}>{file}</option>)}</select><small>Add the child package in Files first.</small></label><JsonField label="Child permissions" value={config.permissions} onSave={value => editConfig('permissions', value)} validate={value => !!value && typeof value === 'object' && !Array.isArray(value)} hint="Explicit model, MCP, sandbox and secret permissions for the child." /></> : null}
      <button className="button full setup-next" onClick={() => setTab('ports')}>Connect inputs & define outputs<ArrowRight size={15} /></button>
      <details className="field-details"><summary>Run conditions & advanced options</summary><TextField label="Run condition (CEL)" value={node.when ?? ''} optional onSave={value => onEdit('when', value || undefined)} hint="Leave blank to run whenever inputs are ready." /><TextField label="Wait for blocks" value={(node.needs ?? []).join(', ')} optional onSave={value => onEdit('needs', value ? value.split(',').map(value => value.trim()).filter(Boolean) : undefined)} hint="Comma-separated block IDs. This waits without transferring data." /><button className="text-button" onClick={onSource}><Braces size={14} />Open YAML</button></details>
    </> : <>
      <PortEditor key={id + 'inputs'} ports={node.inputs ?? {}} direction="inputs" graph={graph} imports={importedGraphs} nodeId={id} onChange={inputs => onEdit('inputs', inputs)} allowFiles={node.type !== 'llm'} schemas={Object.keys(resources.schemas ?? {})} />
      <PortEditor key={id + 'outputs'} ports={outputs} direction="outputs" graph={graph} imports={importedGraphs} onChange={outputs => onEdit('outputs', outputs)} editable={!['switch', 'foreach', 'loop', 'pipeline'].includes(node.type)} minimum={1} canAdd={node.type !== 'tool'} allowFiles={['agent', 'code'].includes(node.type)} schemas={Object.keys(resources.schemas ?? {})} />
      {['switch', 'foreach', 'loop', 'pipeline'].includes(node.type) ? <p className="setup-hint">These outputs come from {node.type === 'pipeline' ? 'the child pipeline exports' : node.type === 'switch' ? 'the selected route' : 'the body graph exports'}. Edit them at their source.</p> : null}
    </>}</div></aside>;
}
