// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const insertArtifact = `-- name: InsertArtifact :execresult
INSERT INTO knotra_artifacts(id,document) VALUES($1,$2)
`

type InsertArtifactParams struct {
	ID       string
	Document []byte
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertArtifact, arg.ID, arg.Document)
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT document FROM knotra_artifacts WHERE published AND ($1::text='' OR id<$1) ORDER BY id DESC LIMIT 101
`

func (q *Queries) ListArtifacts(ctx context.Context, dollar_1 string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listArtifacts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readArtifact = `-- name: ReadArtifact :one
SELECT document FROM knotra_artifacts WHERE id=$1 AND published
`

func (q *Queries) ReadArtifact(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, readArtifact, id)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const readArtifactMetadata = `-- name: ReadArtifactMetadata :one
SELECT document FROM knotra_artifacts WHERE id=$1
`

func (q *Queries) ReadArtifactMetadata(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, readArtifactMetadata, id)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const registerArtifact = `-- name: RegisterArtifact :execresult
INSERT INTO knotra_artifacts(id,document,published) VALUES($1,$2,true)
`

type RegisterArtifactParams struct {
	ID       string
	Document []byte
}

func (q *Queries) RegisterArtifact(ctx context.Context, arg RegisterArtifactParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, registerArtifact, arg.ID, arg.Document)
}
