// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const databaseTime = `-- name: DatabaseTime :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) DatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const decreaseActiveAttempts = `-- name: DecreaseActiveAttempts :execresult
UPDATE knotra_execution_scopes SET active_attempts=active_attempts-1 WHERE run_id=$1 AND id=$2
`

type DecreaseActiveAttemptsParams struct {
	RunID string
	ID    string
}

func (q *Queries) DecreaseActiveAttempts(ctx context.Context, arg DecreaseActiveAttemptsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, decreaseActiveAttempts, arg.RunID, arg.ID)
}

const drainWorker = `-- name: DrainWorker :execresult
UPDATE knotra_workers SET draining=true WHERE id=$1 AND engine_id=$2
`

type DrainWorkerParams struct {
	ID       string
	EngineID string
}

func (q *Queries) DrainWorker(ctx context.Context, arg DrainWorkerParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, drainWorker, arg.ID, arg.EngineID)
}

const increaseActiveAttempts = `-- name: IncreaseActiveAttempts :execresult
UPDATE knotra_execution_scopes SET active_attempts=active_attempts+1 WHERE run_id=$1 AND id=$2
`

type IncreaseActiveAttemptsParams struct {
	RunID string
	ID    string
}

func (q *Queries) IncreaseActiveAttempts(ctx context.Context, arg IncreaseActiveAttemptsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, increaseActiveAttempts, arg.RunID, arg.ID)
}

const incrementRunRevision = `-- name: IncrementRunRevision :execresult
UPDATE knotra_runs SET state_revision=state_revision+1 WHERE id=$1
`

func (q *Queries) IncrementRunRevision(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, incrementRunRevision, id)
}

const lockAttemptLease = `-- name: LockAttemptLease :one
SELECT lease_expires_at FROM knotra_execution_attempts
		WHERE run_id=$1 AND instance_id=$2 AND number=$3 AND state='claimed' AND owner=$4 AND ownership_generation=$5 FOR UPDATE
`

type LockAttemptLeaseParams struct {
	RunID               string
	InstanceID          string
	Number              int
	Owner               *string
	OwnershipGeneration int64
}

func (q *Queries) LockAttemptLease(ctx context.Context, arg LockAttemptLeaseParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, lockAttemptLease,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
		arg.Owner,
		arg.OwnershipGeneration,
	)
	var lease_expires_at *time.Time
	err := row.Scan(&lease_expires_at)
	return lease_expires_at, err
}

const lockClaimAttempt = `-- name: LockClaimAttempt :one
SELECT state,dispatch_generation,ownership_generation FROM knotra_execution_attempts
		WHERE run_id=$1 AND instance_id=$2 AND number=$3 FOR UPDATE
`

type LockClaimAttemptParams struct {
	RunID      string
	InstanceID string
	Number     int
}

type LockClaimAttemptRow struct {
	State               string
	DispatchGeneration  int64
	OwnershipGeneration int64
}

func (q *Queries) LockClaimAttempt(ctx context.Context, arg LockClaimAttemptParams) (LockClaimAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockClaimAttempt, arg.RunID, arg.InstanceID, arg.Number)
	var i LockClaimAttemptRow
	err := row.Scan(&i.State, &i.DispatchGeneration, &i.OwnershipGeneration)
	return i, err
}

const lockClaimNode = `-- name: LockClaimNode :one
SELECT n.state AS node_state,n.attempt_number,n.execution_request,n.deadline,g.state AS graph_state,g.scopes,
		n.node_id,g.pipeline,g.graph_path,g.parent_instance_id,g.iteration_index,n.started_at,(r.plan->>'digest')::text AS plan_digest
		FROM knotra_execution_nodes n JOIN knotra_execution_graphs g ON g.run_id=n.run_id AND g.id=n.graph_id
		JOIN knotra_runs r ON r.id=n.run_id
		WHERE n.run_id=$1 AND n.id=$2 FOR UPDATE OF n
`

type LockClaimNodeParams struct {
	RunID string
	ID    string
}

type LockClaimNodeRow struct {
	NodeState        string
	AttemptNumber    int
	ExecutionRequest []byte
	Deadline         *time.Time
	GraphState       string
	Scopes           []byte
	NodeID           string
	Pipeline         string
	GraphPath        string
	ParentInstanceID *string
	IterationIndex   *int
	StartedAt        *time.Time
	PlanDigest       string
}

func (q *Queries) LockClaimNode(ctx context.Context, arg LockClaimNodeParams) (LockClaimNodeRow, error) {
	row := q.db.QueryRow(ctx, lockClaimNode, arg.RunID, arg.ID)
	var i LockClaimNodeRow
	err := row.Scan(
		&i.NodeState,
		&i.AttemptNumber,
		&i.ExecutionRequest,
		&i.Deadline,
		&i.GraphState,
		&i.Scopes,
		&i.NodeID,
		&i.Pipeline,
		&i.GraphPath,
		&i.ParentInstanceID,
		&i.IterationIndex,
		&i.StartedAt,
		&i.PlanDigest,
	)
	return i, err
}

const lockClaimScopes = `-- name: LockClaimScopes :many
SELECT id,limits,active_attempts FROM knotra_execution_scopes
		WHERE run_id=$1 AND id=ANY($2::text[]) ORDER BY id FOR UPDATE
`

type LockClaimScopesParams struct {
	RunID    string
	ScopeIDs []string
}

type LockClaimScopesRow struct {
	ID             string
	Limits         []byte
	ActiveAttempts int
}

func (q *Queries) LockClaimScopes(ctx context.Context, arg LockClaimScopesParams) ([]LockClaimScopesRow, error) {
	rows, err := q.db.Query(ctx, lockClaimScopes, arg.RunID, arg.ScopeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockClaimScopesRow{}
	for rows.Next() {
		var i LockClaimScopesRow
		if err := rows.Scan(&i.ID, &i.Limits, &i.ActiveAttempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCompletedAttempt = `-- name: LockCompletedAttempt :one
SELECT state FROM knotra_execution_attempts WHERE run_id=$1 AND instance_id=$2 AND number=$3
		AND owner=$4 AND ownership_generation=$5 FOR UPDATE
`

type LockCompletedAttemptParams struct {
	RunID               string
	InstanceID          string
	Number              int
	Owner               *string
	OwnershipGeneration int64
}

func (q *Queries) LockCompletedAttempt(ctx context.Context, arg LockCompletedAttemptParams) (string, error) {
	row := q.db.QueryRow(ctx, lockCompletedAttempt,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
		arg.Owner,
		arg.OwnershipGeneration,
	)
	var state string
	err := row.Scan(&state)
	return state, err
}

const lockOwnedNode = `-- name: LockOwnedNode :one
SELECT state,attempt_number,deadline FROM knotra_execution_nodes WHERE run_id=$1 AND id=$2 FOR UPDATE
`

type LockOwnedNodeParams struct {
	RunID string
	ID    string
}

type LockOwnedNodeRow struct {
	State         string
	AttemptNumber int
	Deadline      *time.Time
}

func (q *Queries) LockOwnedNode(ctx context.Context, arg LockOwnedNodeParams) (LockOwnedNodeRow, error) {
	row := q.db.QueryRow(ctx, lockOwnedNode, arg.RunID, arg.ID)
	var i LockOwnedNodeRow
	err := row.Scan(&i.State, &i.AttemptNumber, &i.Deadline)
	return i, err
}

const lockReservedScopeIDs = `-- name: LockReservedScopeIDs :many
SELECT s.id FROM knotra_execution_scopes s JOIN knotra_execution_slots r
		ON r.run_id=s.run_id AND r.scope_id=s.id WHERE r.run_id=$1 AND r.instance_id=$2 AND r.attempt_number=$3
		AND r.ownership_generation=$4 AND r.released_at IS NULL ORDER BY s.id FOR UPDATE OF s
`

type LockReservedScopeIDsParams struct {
	RunID               string
	InstanceID          string
	AttemptNumber       int
	OwnershipGeneration int64
}

func (q *Queries) LockReservedScopeIDs(ctx context.Context, arg LockReservedScopeIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, lockReservedScopeIDs,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.OwnershipGeneration,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkerHeartbeat = `-- name: LockWorkerHeartbeat :one
SELECT heartbeat_at FROM knotra_workers WHERE id=$1 AND engine_id=$2 FOR UPDATE
`

type LockWorkerHeartbeatParams struct {
	ID       string
	EngineID string
}

func (q *Queries) LockWorkerHeartbeat(ctx context.Context, arg LockWorkerHeartbeatParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, lockWorkerHeartbeat, arg.ID, arg.EngineID)
	var heartbeat_at time.Time
	err := row.Scan(&heartbeat_at)
	return heartbeat_at, err
}

const markAttemptForDispatch = `-- name: MarkAttemptForDispatch :execresult
UPDATE knotra_execution_attempts SET dispatch_pending=true
			WHERE run_id=$1 AND instance_id=$2 AND number=$3
`

type MarkAttemptForDispatchParams struct {
	RunID      string
	InstanceID string
	Number     int
}

func (q *Queries) MarkAttemptForDispatch(ctx context.Context, arg MarkAttemptForDispatchParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, markAttemptForDispatch, arg.RunID, arg.InstanceID, arg.Number)
}

const markPausedAttemptForDispatch = `-- name: MarkPausedAttemptForDispatch :execresult
UPDATE knotra_execution_attempts SET dispatch_pending=true
			WHERE run_id=$1 AND instance_id=$2 AND number=$3 AND state='ready' AND dispatch_generation=$4
`

type MarkPausedAttemptForDispatchParams struct {
	RunID              string
	InstanceID         string
	Number             int
	DispatchGeneration int64
}

func (q *Queries) MarkPausedAttemptForDispatch(ctx context.Context, arg MarkPausedAttemptForDispatchParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, markPausedAttemptForDispatch,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
		arg.DispatchGeneration,
	)
}

const readClaimWorker = `-- name: ReadClaimWorker :one
SELECT heartbeat_at,draining,($1::integer=ANY(scheduler_versions) AND $2::integer=ANY(state_format_versions)
    AND COALESCE(capabilities->>'role','all') IN ('all','executor')) AS compatible
		FROM knotra_workers WHERE id=$3 AND engine_id=$4 FOR SHARE
`

type ReadClaimWorkerParams struct {
	SchedulerVersion   int
	StateFormatVersion int
	ID                 string
	EngineID           string
}

type ReadClaimWorkerRow struct {
	HeartbeatAt time.Time
	Draining    bool
	Compatible  *bool
}

func (q *Queries) ReadClaimWorker(ctx context.Context, arg ReadClaimWorkerParams) (ReadClaimWorkerRow, error) {
	row := q.db.QueryRow(ctx, readClaimWorker,
		arg.SchedulerVersion,
		arg.StateFormatVersion,
		arg.ID,
		arg.EngineID,
	)
	var i ReadClaimWorkerRow
	err := row.Scan(&i.HeartbeatAt, &i.Draining, &i.Compatible)
	return i, err
}

const readOwnedWorkerHeartbeat = `-- name: ReadOwnedWorkerHeartbeat :one
SELECT heartbeat_at FROM knotra_workers WHERE id=$1 AND engine_id=$2
		AND $3::integer=ANY(scheduler_versions) AND $4::integer=ANY(state_format_versions) FOR SHARE
`

type ReadOwnedWorkerHeartbeatParams struct {
	ID                 string
	EngineID           string
	SchedulerVersion   int
	StateFormatVersion int
}

func (q *Queries) ReadOwnedWorkerHeartbeat(ctx context.Context, arg ReadOwnedWorkerHeartbeatParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, readOwnedWorkerHeartbeat,
		arg.ID,
		arg.EngineID,
		arg.SchedulerVersion,
		arg.StateFormatVersion,
	)
	var heartbeat_at time.Time
	err := row.Scan(&heartbeat_at)
	return heartbeat_at, err
}

const registerWorker = `-- name: RegisterWorker :execresult
INSERT INTO knotra_workers(id,engine_id,host_id,scheduler_versions,state_format_versions,capabilities)
		VALUES($1,$2,$3,ARRAY[$4::integer]::integer[],ARRAY[$5::integer]::integer[],$6::jsonb) ON CONFLICT DO NOTHING
`

type RegisterWorkerParams struct {
	ID           string
	EngineID     string
	HostID       string
	Column4      int
	Column5      int
	Capabilities []byte
}

func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, registerWorker,
		arg.ID,
		arg.EngineID,
		arg.HostID,
		arg.Column4,
		arg.Column5,
		arg.Capabilities,
	)
}

const releaseReservedSlots = `-- name: ReleaseReservedSlots :execresult
UPDATE knotra_execution_slots SET released_at=clock_timestamp()
		WHERE run_id=$1 AND instance_id=$2 AND attempt_number=$3 AND ownership_generation=$4 AND released_at IS NULL
`

type ReleaseReservedSlotsParams struct {
	RunID               string
	InstanceID          string
	AttemptNumber       int
	OwnershipGeneration int64
}

func (q *Queries) ReleaseReservedSlots(ctx context.Context, arg ReleaseReservedSlotsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, releaseReservedSlots,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.OwnershipGeneration,
	)
}

const renewAttempt = `-- name: RenewAttempt :one
UPDATE knotra_execution_attempts SET lease_expires_at=LEAST($1,$2,
		(SELECT n.deadline FROM knotra_execution_nodes n WHERE n.run_id=$3 AND n.id=$4))
		WHERE run_id=$3 AND instance_id=$4 AND number=$5 RETURNING lease_expires_at
`

type RenewAttemptParams struct {
	LeaseExpiresAt *time.Time
	RootDeadline   *time.Time
	RunID          string
	ID             string
	Number         int
}

func (q *Queries) RenewAttempt(ctx context.Context, arg RenewAttemptParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, renewAttempt,
		arg.LeaseExpiresAt,
		arg.RootDeadline,
		arg.RunID,
		arg.ID,
		arg.Number,
	)
	var lease_expires_at *time.Time
	err := row.Scan(&lease_expires_at)
	return lease_expires_at, err
}

const reserveAttemptSlot = `-- name: ReserveAttemptSlot :execresult
INSERT INTO knotra_execution_slots(run_id,instance_id,attempt_number,scope_id,ownership_generation)
			VALUES($1,$2,$3,$4,$5)
`

type ReserveAttemptSlotParams struct {
	RunID               string
	InstanceID          string
	AttemptNumber       int
	ScopeID             string
	OwnershipGeneration int64
}

func (q *Queries) ReserveAttemptSlot(ctx context.Context, arg ReserveAttemptSlotParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, reserveAttemptSlot,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.ScopeID,
		arg.OwnershipGeneration,
	)
}

const setAttemptClaimed = `-- name: SetAttemptClaimed :execresult
UPDATE knotra_execution_attempts SET state='claimed',dispatch_pending=false,owner=$4,
		ownership_generation=$5,lease_expires_at=$6,outcome_key=$7 WHERE run_id=$1 AND instance_id=$2 AND number=$3
`

type SetAttemptClaimedParams struct {
	RunID               string
	InstanceID          string
	Number              int
	Owner               *string
	OwnershipGeneration int64
	LeaseExpiresAt      *time.Time
	OutcomeKey          *string
}

func (q *Queries) SetAttemptClaimed(ctx context.Context, arg SetAttemptClaimedParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setAttemptClaimed,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
		arg.Owner,
		arg.OwnershipGeneration,
		arg.LeaseExpiresAt,
		arg.OutcomeKey,
	)
}

const setNodeRunning = `-- name: SetNodeRunning :execresult
UPDATE knotra_execution_nodes SET state='running',started_at=$3,revision=revision+1 WHERE run_id=$1 AND id=$2
`

type SetNodeRunningParams struct {
	RunID     string
	ID        string
	StartedAt *time.Time
}

func (q *Queries) SetNodeRunning(ctx context.Context, arg SetNodeRunningParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setNodeRunning, arg.RunID, arg.ID, arg.StartedAt)
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :execresult
UPDATE knotra_workers SET heartbeat_at=$2 WHERE id=$1
`

type UpdateWorkerHeartbeatParams struct {
	ID          string
	HeartbeatAt time.Time
}

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateWorkerHeartbeat, arg.ID, arg.HeartbeatAt)
}
