// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const applyWake = `-- name: ApplyWake :execresult
UPDATE knotra_runs SET applied_generation=wake_generation,state_revision=state_revision+1,dirty_since=NULL WHERE id=$1
`

func (q *Queries) ApplyWake(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, applyWake, id)
}

const insertRootDeadline = `-- name: InsertRootDeadline :execresult
INSERT INTO knotra_execution_timers(run_id,id,generation,kind,due_at) VALUES($1,'root_deadline',1,'run_deadline',$2)
`

type InsertRootDeadlineParams struct {
	RunID string
	DueAt time.Time
}

func (q *Queries) InsertRootDeadline(ctx context.Context, arg InsertRootDeadlineParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertRootDeadline, arg.RunID, arg.DueAt)
}

const insertRootScope = `-- name: InsertRootScope :execresult
INSERT INTO knotra_execution_scopes(run_id,id,limits) VALUES($1,$1,$2)
`

type InsertRootScopeParams struct {
	RunID  string
	Limits []byte
}

func (q *Queries) InsertRootScope(ctx context.Context, arg InsertRootScopeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertRootScope, arg.RunID, arg.Limits)
}

const lockExecutionRun = `-- name: LockExecutionRun :one
WITH locked AS MATERIALIZED (
SELECT backend,scheduler_version,state_format_version,admitted_at,execution_deadline,
		state_revision,wake_generation,applied_generation,cancel_requested,admission_paused,stop_cause,(document->>'status')::text AS status,graph_cursor,graph_scan_again,delivery_cursor
		FROM knotra_runs WHERE id=$1 FOR UPDATE
)
SELECT locked.backend, locked.scheduler_version, locked.state_format_version, locked.admitted_at, locked.execution_deadline, locked.state_revision, locked.wake_generation, locked.applied_generation, locked.cancel_requested, locked.admission_paused, locked.stop_cause, locked.status, locked.graph_cursor, locked.graph_scan_again, locked.delivery_cursor,clock_timestamp()::timestamptz AS now FROM locked
`

type LockExecutionRunRow struct {
	Backend            string
	SchedulerVersion   int
	StateFormatVersion int
	AdmittedAt         time.Time
	ExecutionDeadline  *time.Time
	StateRevision      int64
	WakeGeneration     int64
	AppliedGeneration  int64
	CancelRequested    bool
	AdmissionPaused    bool
	StopCause          []byte
	Status             string
	GraphCursor        string
	GraphScanAgain     bool
	DeliveryCursor     string
	Now                time.Time
}

// Materialize the locked row before evaluating the database clock. Sampling
// in the inner SELECT would happen before a contended FOR UPDATE finishes.
func (q *Queries) LockExecutionRun(ctx context.Context, id string) (LockExecutionRunRow, error) {
	row := q.db.QueryRow(ctx, lockExecutionRun, id)
	var i LockExecutionRunRow
	err := row.Scan(
		&i.Backend,
		&i.SchedulerVersion,
		&i.StateFormatVersion,
		&i.AdmittedAt,
		&i.ExecutionDeadline,
		&i.StateRevision,
		&i.WakeGeneration,
		&i.AppliedGeneration,
		&i.CancelRequested,
		&i.AdmissionPaused,
		&i.StopCause,
		&i.Status,
		&i.GraphCursor,
		&i.GraphScanAgain,
		&i.DeliveryCursor,
		&i.Now,
	)
	return i, err
}

const nextExecutionEventSequence = `-- name: NextExecutionEventSequence :one
UPDATE knotra_runs SET execution_event_sequence=execution_event_sequence+1,state_revision=state_revision+1
		WHERE id=$1 RETURNING execution_event_sequence
`

func (q *Queries) NextExecutionEventSequence(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, nextExecutionEventSequence, id)
	var execution_event_sequence int64
	err := row.Scan(&execution_event_sequence)
	return execution_event_sequence, err
}

const setRiverAdmission = `-- name: SetRiverAdmission :execresult
UPDATE knotra_runs SET backend='river',scheduler_version=$2,state_format_version=$3,
		admitted_at=$4,execution_deadline=$5,wake_generation=1,dirty_since=$4 WHERE id=$1
`

type SetRiverAdmissionParams struct {
	ID                 string
	SchedulerVersion   int
	StateFormatVersion int
	AdmittedAt         time.Time
	ExecutionDeadline  *time.Time
}

func (q *Queries) SetRiverAdmission(ctx context.Context, arg SetRiverAdmissionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setRiverAdmission,
		arg.ID,
		arg.SchedulerVersion,
		arg.StateFormatVersion,
		arg.AdmittedAt,
		arg.ExecutionDeadline,
	)
}

const wakeExecution = `-- name: WakeExecution :one
UPDATE knotra_runs SET wake_generation=wake_generation+1,state_revision=state_revision+1,
    dirty_since=COALESCE(dirty_since,clock_timestamp()) WHERE id=$1 RETURNING wake_generation
`

func (q *Queries) WakeExecution(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, wakeExecution, id)
	var wake_generation int64
	err := row.Scan(&wake_generation)
	return wake_generation, err
}
