// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graphs.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const addExecutionChild = `-- name: AddExecutionChild :execresult
UPDATE knotra_execution_controls SET active_children=active_children+1
WHERE run_id=$1 AND instance_id=$2
`

type AddExecutionChildParams struct {
	RunID      string
	InstanceID string
}

func (q *Queries) AddExecutionChild(ctx context.Context, arg AddExecutionChildParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, addExecutionChild, arg.RunID, arg.InstanceID)
}

const finishExecutionChild = `-- name: FinishExecutionChild :execresult
UPDATE knotra_execution_controls SET active_children=active_children-1,
    succeeded_children=succeeded_children+CASE WHEN $1::text='succeeded' THEN 1 ELSE 0 END,
    failed_children=failed_children+CASE WHEN $1::text IN ('failed','cancelled') THEN 1 ELSE 0 END
WHERE run_id=$2 AND instance_id=$3 AND active_children>0
`

type FinishExecutionChildParams struct {
	State      string
	RunID      string
	InstanceID string
}

func (q *Queries) FinishExecutionChild(ctx context.Context, arg FinishExecutionChildParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, finishExecutionChild, arg.State, arg.RunID, arg.InstanceID)
}

const finishGraphScan = `-- name: FinishGraphScan :execresult
UPDATE knotra_runs SET graph_cursor='',graph_scan_again=false,state_revision=state_revision+1 WHERE id=$1
`

func (q *Queries) FinishGraphScan(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, finishGraphScan, id)
}

const hasActiveExecution = `-- name: HasActiveExecution :one
SELECT EXISTS(
    SELECT 1 FROM knotra_execution_graphs g WHERE g.run_id=$1 AND g.state IN ('pending','running')
    UNION ALL
    SELECT 1 FROM knotra_execution_attempts a WHERE a.run_id=$1 AND a.state='claimed'
)
`

func (q *Queries) HasActiveExecution(ctx context.Context, runID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveExecution, runID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasActiveNodesOutsideSelection = `-- name: HasActiveNodesOutsideSelection :one
SELECT EXISTS(SELECT 1 FROM knotra_execution_nodes WHERE run_id=$1 AND graph_id=$2
    AND state NOT IN ('succeeded','skipped','failed','cancelled') AND NOT (id=ANY($3::text[])))
`

type HasActiveNodesOutsideSelectionParams struct {
	RunID       string
	GraphID     string
	InstanceIds []string
}

func (q *Queries) HasActiveNodesOutsideSelection(ctx context.Context, arg HasActiveNodesOutsideSelectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveNodesOutsideSelection, arg.RunID, arg.GraphID, arg.InstanceIds)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasUnresolvedOutsideSelection = `-- name: HasUnresolvedOutsideSelection :one
SELECT EXISTS(SELECT 1 FROM knotra_execution_nodes WHERE run_id=$1
    AND state='waiting_resolution' AND NOT (id=ANY($2::text[])))
`

type HasUnresolvedOutsideSelectionParams struct {
	RunID       string
	InstanceIds []string
}

func (q *Queries) HasUnresolvedOutsideSelection(ctx context.Context, arg HasUnresolvedOutsideSelectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnresolvedOutsideSelection, arg.RunID, arg.InstanceIds)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertExecutionAttempt = `-- name: InsertExecutionAttempt :execresult
INSERT INTO knotra_execution_attempts(run_id,instance_id,number,dispatch_generation,dispatch_pending,state)
		VALUES($1,$2,$3,$4,$5,'ready')
`

type InsertExecutionAttemptParams struct {
	RunID              string
	InstanceID         string
	Number             int
	DispatchGeneration int64
	DispatchPending    bool
}

func (q *Queries) InsertExecutionAttempt(ctx context.Context, arg InsertExecutionAttemptParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertExecutionAttempt,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
		arg.DispatchGeneration,
		arg.DispatchPending,
	)
}

const insertExecutionGraph = `-- name: InsertExecutionGraph :execresult
INSERT INTO knotra_execution_graphs(run_id,id,parent_instance_id,address,pipeline,graph_path,
		inputs,permissions,scopes,deadline,state,revision,iteration_index) VALUES($1,$2,NULLIF($3::text,''),$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type InsertExecutionGraphParams struct {
	RunID            string
	ID               string
	ParentInstanceID string
	Address          string
	Pipeline         string
	GraphPath        string
	Inputs           []byte
	Permissions      []byte
	Scopes           []byte
	Deadline         time.Time
	State            string
	Revision         int64
	IterationIndex   *int
}

func (q *Queries) InsertExecutionGraph(ctx context.Context, arg InsertExecutionGraphParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertExecutionGraph,
		arg.RunID,
		arg.ID,
		arg.ParentInstanceID,
		arg.Address,
		arg.Pipeline,
		arg.GraphPath,
		arg.Inputs,
		arg.Permissions,
		arg.Scopes,
		arg.Deadline,
		arg.State,
		arg.Revision,
		arg.IterationIndex,
	)
}

const insertExecutionScope = `-- name: InsertExecutionScope :execresult
INSERT INTO knotra_execution_scopes(run_id,id,limits) VALUES($1,$2,$3)
`

type InsertExecutionScopeParams struct {
	RunID  string
	ID     string
	Limits []byte
}

func (q *Queries) InsertExecutionScope(ctx context.Context, arg InsertExecutionScopeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertExecutionScope, arg.RunID, arg.ID, arg.Limits)
}

const listRunnableGraphs = `-- name: ListRunnableGraphs :many
SELECT g.id,g.address
FROM knotra_execution_graphs g
WHERE g.run_id=$1 AND g.state IN ('pending','running')
AND ($2::text='' OR EXISTS(
    SELECT 1 FROM knotra_execution_nodes n WHERE n.run_id=g.run_id
        AND n.graph_id=g.id AND n.id=$2::text))
AND (
    g.address>$3::text
    OR EXISTS(SELECT 1 FROM knotra_execution_nodes n WHERE n.run_id=g.run_id
        AND n.graph_id=g.id AND n.id=$2::text)
    OR EXISTS(SELECT 1 FROM knotra_execution_nodes n JOIN knotra_requests q
        ON q.run_id=n.run_id AND q.id=n.current_request_id
        WHERE n.run_id=g.run_id AND n.graph_id=g.id
            AND n.state IN ('waiting_human','waiting_resolution')
            AND q.status IN ('answered','resolved'))
)
ORDER BY
    EXISTS(SELECT 1 FROM knotra_execution_nodes n WHERE n.run_id=g.run_id
        AND n.graph_id=g.id AND n.id=$2::text) DESC,
    EXISTS(SELECT 1 FROM knotra_execution_nodes n JOIN knotra_requests q
        ON q.run_id=n.run_id AND q.id=n.current_request_id
        WHERE n.run_id=g.run_id AND n.graph_id=g.id
            AND n.state IN ('waiting_human','waiting_resolution')
            AND q.status IN ('answered','resolved')) DESC,
    g.address
LIMIT 64
`

type ListRunnableGraphsParams struct {
	RunID           string
	FocusInstanceID string
	GraphCursor     string
}

type ListRunnableGraphsRow struct {
	ID      string
	Address string
}

func (q *Queries) ListRunnableGraphs(ctx context.Context, arg ListRunnableGraphsParams) ([]ListRunnableGraphsRow, error) {
	rows, err := q.db.Query(ctx, listRunnableGraphs, arg.RunID, arg.FocusInstanceID, arg.GraphCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunnableGraphsRow{}
	for rows.Next() {
		var i ListRunnableGraphsRow
		if err := rows.Scan(&i.ID, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGraphScanProgress = `-- name: MarkGraphScanProgress :execresult
UPDATE knotra_runs SET graph_scan_again=true WHERE id=$1
`

func (q *Queries) MarkGraphScanProgress(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, markGraphScanProgress, id)
}

const readChildExecutionGraphs = `-- name: ReadChildExecutionGraphs :many
SELECT CASE WHEN $3::text[] IS NULL THEN to_jsonb(children) ELSE
    jsonb_build_object('run_id',children.run_id,'id',children.id,'parent_instance_id',children.parent_instance_id,
        'state',children.state,'outputs',children.outputs,'failure',children.failure,'iteration_index',children.iteration_index)
    END::jsonb
FROM (
    SELECT g.run_id, g.id, g.parent_instance_id, g.address, g.pipeline, g.graph_path, g.inputs, g.permissions, g.scopes, g.deadline, g.state, g.materialization_cursor, g.outputs, g.failure, g.revision, g.iteration_index
    FROM knotra_execution_nodes n
    JOIN knotra_execution_controls c ON c.run_id=n.run_id AND c.instance_id=n.id
    JOIN LATERAL (
        (SELECT g.run_id, g.id, g.parent_instance_id, g.address, g.pipeline, g.graph_path, g.inputs, g.permissions, g.scopes, g.deadline, g.state, g.materialization_cursor, g.outputs, g.failure, g.revision, g.iteration_index FROM knotra_execution_graphs g
        WHERE g.run_id=c.run_id AND g.parent_instance_id=c.instance_id AND g.state IN ('failed','cancelled')
        ORDER BY g.iteration_index,g.id LIMIT 1)
        UNION ALL
        (SELECT g.run_id, g.id, g.parent_instance_id, g.address, g.pipeline, g.graph_path, g.inputs, g.permissions, g.scopes, g.deadline, g.state, g.materialization_cursor, g.outputs, g.failure, g.revision, g.iteration_index FROM knotra_execution_graphs g
        WHERE g.run_id=c.run_id AND g.parent_instance_id=c.instance_id AND g.state='succeeded'
            AND c.active_children=0 AND c.failed_children=0
            AND c.next_position=c.element_count
            AND g.iteration_index>=c.collection_position
        ORDER BY g.iteration_index,g.id LIMIT 64)
    ) g ON true
    WHERE n.run_id=$1 AND n.graph_id=$2 AND c.kind='foreach'
        AND ($3::text[] IS NULL OR n.id=ANY($3::text[]))
    UNION ALL
    SELECT g.run_id, g.id, g.parent_instance_id, g.address, g.pipeline, g.graph_path, g.inputs, g.permissions, g.scopes, g.deadline, g.state, g.materialization_cursor, g.outputs, g.failure, g.revision, g.iteration_index
    FROM knotra_execution_nodes n
    JOIN knotra_execution_controls c ON c.run_id=n.run_id AND c.instance_id=n.id
    JOIN knotra_execution_graphs g ON g.run_id=c.run_id AND g.id=c.child_graph_id
    WHERE n.run_id=$1 AND n.graph_id=$2 AND c.kind IN ('pipeline','loop')
        AND ($3::text[] IS NULL OR n.id=ANY($3::text[]))
) children
ORDER BY children.parent_instance_id,children.iteration_index,children.id
`

type ReadChildExecutionGraphsParams struct {
	RunID       string
	GraphID     string
	InstanceIds []string
}

func (q *Queries) ReadChildExecutionGraphs(ctx context.Context, arg ReadChildExecutionGraphsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, readChildExecutionGraphs, arg.RunID, arg.GraphID, arg.InstanceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var column_1 []byte
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readExecutionAttempts = `-- name: ReadExecutionAttempts :many
SELECT (to_jsonb(a) || jsonb_build_object(
    'runId',a.run_id,'instanceId',a.instance_id,'Ownership',CASE WHEN a.owner IS NULL THEN NULL ELSE jsonb_build_object(
    'runId',a.run_id,'instanceId',a.instance_id,'number',a.number,'workerId',a.owner,'generation',a.ownership_generation) END))::jsonb
FROM knotra_execution_attempts a JOIN knotra_execution_nodes n ON n.run_id=a.run_id AND n.id=a.instance_id
WHERE a.run_id=$1 AND n.graph_id=$2 AND a.number=n.attempt_number
    AND ($3::text[] IS NULL OR n.id=ANY($3::text[])) ORDER BY a.instance_id
`

type ReadExecutionAttemptsParams struct {
	RunID       string
	GraphID     string
	InstanceIds []string
}

func (q *Queries) ReadExecutionAttempts(ctx context.Context, arg ReadExecutionAttemptsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, readExecutionAttempts, arg.RunID, arg.GraphID, arg.InstanceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var column_1 []byte
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readExecutionControls = `-- name: ReadExecutionControls :many
SELECT jsonb_build_object('run_id',c.run_id,'instance_id',c.instance_id,'kind',c.kind,
    'next_position',c.next_position,'collection_position',c.collection_position,'active_children',c.active_children,
    'succeeded_children',c.succeeded_children,'failed_children',c.failed_children,'iteration',c.iteration,
    'element_count',c.element_count,'concurrency',c.concurrency,'current_element',c.elements->c.next_position,
    'carry',c.carry,'child_graph_id',c.child_graph_id,'revision',c.revision)::jsonb
FROM knotra_execution_controls c
JOIN knotra_execution_nodes n ON n.run_id=c.run_id AND n.id=c.instance_id
WHERE c.run_id=$1 AND n.graph_id=$2
    AND ($3::text[] IS NULL OR n.id=ANY($3::text[]))
ORDER BY c.instance_id
`

type ReadExecutionControlsParams struct {
	RunID       string
	GraphID     string
	InstanceIds []string
}

func (q *Queries) ReadExecutionControls(ctx context.Context, arg ReadExecutionControlsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, readExecutionControls, arg.RunID, arg.GraphID, arg.InstanceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var column_1 []byte
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readExecutionDependencyValues = `-- name: ReadExecutionDependencyValues :many
SELECT jsonb_build_object('run_id',n.run_id,'id',n.id,'graph_id',n.graph_id,
    'node_id',n.node_id,'state',n.state,'outputs',n.outputs)::jsonb
FROM knotra_execution_nodes n WHERE n.run_id=$1 AND n.graph_id=$2
    AND n.node_id=ANY($3::text[]) ORDER BY n.node_id
`

type ReadExecutionDependencyValuesParams struct {
	RunID   string
	GraphID string
	NodeIds []string
}

func (q *Queries) ReadExecutionDependencyValues(ctx context.Context, arg ReadExecutionDependencyValuesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, readExecutionDependencyValues, arg.RunID, arg.GraphID, arg.NodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var column_1 []byte
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readExecutionGraph = `-- name: ReadExecutionGraph :one
SELECT to_jsonb(g) FROM knotra_execution_graphs g WHERE run_id=$1 AND id=$2
`

type ReadExecutionGraphParams struct {
	RunID string
	ID    string
}

func (q *Queries) ReadExecutionGraph(ctx context.Context, arg ReadExecutionGraphParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readExecutionGraph, arg.RunID, arg.ID)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const readExecutionGraphInputValues = `-- name: ReadExecutionGraphInputValues :one
SELECT CASE WHEN $3::text[] IS NULL THEN g.inputs ELSE
    (SELECT COALESCE(jsonb_object_agg(k.name,g.inputs->k.name) FILTER (WHERE g.inputs ? k.name),'{}'::jsonb)
        FROM unnest($3::text[]) k(name)) END::jsonb
FROM knotra_execution_graphs g WHERE g.run_id=$1 AND g.id=$2
`

type ReadExecutionGraphInputValuesParams struct {
	RunID     string
	ID        string
	PortNames []string
}

func (q *Queries) ReadExecutionGraphInputValues(ctx context.Context, arg ReadExecutionGraphInputValuesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readExecutionGraphInputValues, arg.RunID, arg.ID, arg.PortNames)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const readExecutionGraphMetadata = `-- name: ReadExecutionGraphMetadata :one
SELECT jsonb_build_object('run_id',g.run_id,'id',g.id,'parent_instance_id',g.parent_instance_id,
    'address',g.address,'pipeline',g.pipeline,'graph_path',g.graph_path,'permissions',g.permissions,
    'scopes',g.scopes,'deadline',g.deadline,'state',g.state,'materialization_cursor',g.materialization_cursor,
    'outputs',g.outputs,'failure',g.failure,'revision',g.revision,'iteration_index',g.iteration_index)::jsonb
FROM knotra_execution_graphs g WHERE g.run_id=$1 AND g.id=$2
`

type ReadExecutionGraphMetadataParams struct {
	RunID string
	ID    string
}

func (q *Queries) ReadExecutionGraphMetadata(ctx context.Context, arg ReadExecutionGraphMetadataParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readExecutionGraphMetadata, arg.RunID, arg.ID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const readExecutionNode = `-- name: ReadExecutionNode :one
SELECT to_jsonb(n) FROM knotra_execution_nodes n WHERE n.run_id=$1 AND n.id=$2
`

type ReadExecutionNodeParams struct {
	RunID string
	ID    string
}

func (q *Queries) ReadExecutionNode(ctx context.Context, arg ReadExecutionNodeParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readExecutionNode, arg.RunID, arg.ID)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const readExecutionNodeInputValues = `-- name: ReadExecutionNodeInputValues :one
SELECT (SELECT COALESCE(jsonb_object_agg(k.name,n.inputs->k.name) FILTER (WHERE n.inputs ? k.name),'{}'::jsonb)
    FROM unnest($3::text[]) k(name))::jsonb
FROM knotra_execution_nodes n WHERE n.run_id=$1 AND n.id=$2
`

type ReadExecutionNodeInputValuesParams struct {
	RunID     string
	ID        string
	PortNames []string
}

func (q *Queries) ReadExecutionNodeInputValues(ctx context.Context, arg ReadExecutionNodeInputValuesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readExecutionNodeInputValues, arg.RunID, arg.ID, arg.PortNames)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const readExecutionRequests = `-- name: ReadExecutionRequests :many
SELECT (q.document::jsonb || jsonb_build_object(
    'status',q.status,'responseId',q.response_id,'acceptedAt',q.accepted_at,'answer',q.response))::jsonb
FROM knotra_requests q JOIN knotra_execution_nodes n ON n.run_id=q.run_id AND n.current_request_id=q.id
WHERE q.run_id=$1 AND n.graph_id=$2 AND n.state IN ('waiting_human','waiting_resolution')
    AND ($3::text[] IS NULL OR n.id=ANY($3::text[])) ORDER BY q.id
`

type ReadExecutionRequestsParams struct {
	RunID       string
	GraphID     string
	InstanceIds []string
}

func (q *Queries) ReadExecutionRequests(ctx context.Context, arg ReadExecutionRequestsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, readExecutionRequests, arg.RunID, arg.GraphID, arg.InstanceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var column_1 []byte
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readExecutionRetryTimers = `-- name: ReadExecutionRetryTimers :many
SELECT to_jsonb(t) FROM knotra_execution_timers t
JOIN knotra_execution_nodes n ON n.run_id=t.run_id AND n.id=t.instance_id
WHERE t.run_id=$1 AND n.graph_id=$2 AND t.kind='retry' AND t.generation=n.attempt_number
    AND ($3::text[] IS NULL OR n.id=ANY($3::text[]))
`

type ReadExecutionRetryTimersParams struct {
	RunID       string
	GraphID     string
	InstanceIds []string
}

func (q *Queries) ReadExecutionRetryTimers(ctx context.Context, arg ReadExecutionRetryTimersParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, readExecutionRetryTimers, arg.RunID, arg.GraphID, arg.InstanceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readExecutionScopes = `-- name: ReadExecutionScopes :many
SELECT to_jsonb(s) FROM knotra_execution_scopes s WHERE run_id=$1 AND id=ANY($2::text[]) ORDER BY id FOR UPDATE
`

type ReadExecutionScopesParams struct {
	RunID    string
	ScopeIDs []string
}

func (q *Queries) ReadExecutionScopes(ctx context.Context, arg ReadExecutionScopesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, readExecutionScopes, arg.RunID, arg.ScopeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var to_jsonb []byte
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readForeachCollectedOutputs = `-- name: ReadForeachCollectedOutputs :one
SELECT COALESCE(jsonb_object_agg(port.name,port.value),'{}'::jsonb)::jsonb
FROM (
    SELECT p.name,CASE WHEN p.artifact THEN jsonb_build_object('collection',true,'artifacts',
        COALESCE(jsonb_agg(g.outputs->p.name->'artifacts'->0 ORDER BY g.iteration_index) FILTER (WHERE g.id IS NOT NULL),'[]'::jsonb))
    ELSE jsonb_build_object('json',COALESCE(jsonb_agg(g.outputs->p.name->'json' ORDER BY g.iteration_index) FILTER (WHERE g.id IS NOT NULL),'[]'::jsonb)) END AS value
    FROM (
        SELECT unnest($1::text[]) AS name,false AS artifact
        UNION ALL
        SELECT unnest($2::text[]) AS name,true AS artifact
    ) p
    LEFT JOIN knotra_execution_graphs g ON g.run_id=$3 AND g.parent_instance_id=$4 AND g.state='succeeded'
    GROUP BY p.name,p.artifact
) port
`

type ReadForeachCollectedOutputsParams struct {
	JsonPorts     []string
	ArtifactPorts []string
	RunID         string
	InstanceID    *string
}

func (q *Queries) ReadForeachCollectedOutputs(ctx context.Context, arg ReadForeachCollectedOutputsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readForeachCollectedOutputs,
		arg.JsonPorts,
		arg.ArtifactPorts,
		arg.RunID,
		arg.InstanceID,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const readSchedulableNodes = `-- name: ReadSchedulableNodes :many
WITH selected AS MATERIALIZED (
    SELECT n.id,n.node_id,COALESCE(q.status IN ('answered','resolved'),false) AS answered
    FROM knotra_execution_nodes n
    LEFT JOIN knotra_execution_attempts a ON a.run_id=n.run_id AND a.instance_id=n.id AND a.number=n.attempt_number
    LEFT JOIN knotra_execution_controls c ON c.run_id=n.run_id AND c.instance_id=n.id
    LEFT JOIN knotra_execution_graphs child ON child.run_id=c.run_id AND child.id=c.child_graph_id
    LEFT JOIN knotra_requests q ON q.run_id=n.run_id AND q.id=n.current_request_id
    WHERE n.run_id=$1 AND n.graph_id=$3
        AND n.state NOT IN ('succeeded','skipped','failed','cancelled') AND (
        $4::boolean OR n.deadline<=$5::timestamptz
        OR n.id=$2::text
        OR (n.state='pending' AND n.remaining_dependencies=0 AND NOT $6::boolean)
        OR (n.state IN ('ready','running') AND a.state='completed')
        OR (n.state='ready' AND a.dispatch_pending AND NOT $6::boolean)
        OR (n.state='retry_wait' AND NOT $6::boolean AND EXISTS(
            SELECT 1 FROM knotra_execution_timers t WHERE t.run_id=n.run_id AND t.instance_id=n.id
                AND t.kind='retry' AND t.generation=n.attempt_number AND t.due_at<=$5::timestamptz))
        OR (n.state IN ('waiting_human','waiting_resolution') AND q.status IN ('answered','resolved'))
        OR (n.state='running' AND (
            n.node_kind='switch'
            OR (n.node_kind IN ('pipeline','loop','foreach') AND c.instance_id IS NULL)
            OR (c.kind IN ('pipeline','loop') AND (child.state IN ('succeeded','failed','cancelled')
                OR (c.child_graph_id IS NULL AND NOT $6::boolean)))
            OR (c.kind='foreach' AND (c.failed_children>0
                OR (c.active_children=0 AND c.next_position=c.element_count)
                OR (NOT $6::boolean AND c.next_position<c.element_count
                    AND c.active_children<c.concurrency)))
        ))
    )
    ORDER BY n.id=$2::text DESC,answered DESC,n.node_id
    LIMIT LEAST(64,$7::integer)
)
SELECT CASE WHEN n.node_kind='foreach' AND c.instance_id IS NOT NULL THEN
    jsonb_build_object('run_id',n.run_id,'id',n.id,'graph_id',n.graph_id,'node_id',n.node_id,'address',n.address,
        'state',n.state,'outputs',n.outputs,'failure',n.failure,'deadline',n.deadline,'attempt_number',n.attempt_number,
        'revision',n.revision,'started_at',n.started_at,'finished_at',n.finished_at,'reason',n.reason,'inputs_omitted',true)
    ELSE to_jsonb(n) END::jsonb
FROM selected s JOIN knotra_execution_nodes n ON n.run_id=$1 AND n.id=s.id
LEFT JOIN knotra_execution_controls c ON c.run_id=n.run_id AND c.instance_id=n.id
ORDER BY n.id=$2::text DESC,s.answered DESC,s.node_id
`

type ReadSchedulableNodesParams struct {
	RunID           string
	FocusInstanceID string
	GraphID         string
	Stopping        bool
	Now             time.Time
	Paused          bool
	NodeLimit       int
}

func (q *Queries) ReadSchedulableNodes(ctx context.Context, arg ReadSchedulableNodesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, readSchedulableNodes,
		arg.RunID,
		arg.FocusInstanceID,
		arg.GraphID,
		arg.Stopping,
		arg.Now,
		arg.Paused,
		arg.NodeLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var column_1 []byte
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseNodeDependencies = `-- name: ReleaseNodeDependencies :execresult
UPDATE knotra_execution_nodes SET remaining_dependencies=remaining_dependencies-1
WHERE run_id=$1 AND graph_id=$2 AND state='pending'
    AND dependency_node_ids @> ARRAY[$3::text]
`

type ReleaseNodeDependenciesParams struct {
	RunID   string
	GraphID string
	NodeID  string
}

func (q *Queries) ReleaseNodeDependencies(ctx context.Context, arg ReleaseNodeDependenciesParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, releaseNodeDependencies, arg.RunID, arg.GraphID, arg.NodeID)
}

const saveExecutionControl = `-- name: SaveExecutionControl :execresult
INSERT INTO knotra_execution_controls (
    run_id,instance_id,kind,next_position,collection_position,iteration,elements,carry,child_graph_id,revision,concurrency
) VALUES ($1,$2,$3,$4,$5,
    $6,COALESCE($7::jsonb,'[]'::jsonb),$8,NULLIF($9::text,''),$10,$11)
ON CONFLICT (run_id,instance_id) DO UPDATE SET
    next_position=EXCLUDED.next_position,
    collection_position=EXCLUDED.collection_position,
    iteration=EXCLUDED.iteration,
    carry=EXCLUDED.carry,
    child_graph_id=EXCLUDED.child_graph_id,
    revision=EXCLUDED.revision
WHERE knotra_execution_controls.kind=EXCLUDED.kind
    AND knotra_execution_controls.revision=EXCLUDED.revision-1
`

type SaveExecutionControlParams struct {
	RunID              string
	InstanceID         string
	Kind               string
	NextPosition       int
	CollectionPosition int
	Iteration          int
	Elements           []byte
	Carry              []byte
	ChildGraphID       string
	Revision           int64
	Concurrency        int
}

func (q *Queries) SaveExecutionControl(ctx context.Context, arg SaveExecutionControlParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveExecutionControl,
		arg.RunID,
		arg.InstanceID,
		arg.Kind,
		arg.NextPosition,
		arg.CollectionPosition,
		arg.Iteration,
		arg.Elements,
		arg.Carry,
		arg.ChildGraphID,
		arg.Revision,
		arg.Concurrency,
	)
}

const saveExecutionGraph = `-- name: SaveExecutionGraph :execresult
UPDATE knotra_execution_graphs SET state=$1,materialization_cursor=$2,
		inputs=CASE WHEN state='pending' THEN $3::jsonb ELSE inputs END,outputs=$4,failure=$5,revision=$6
		WHERE run_id=$7 AND id=$8 AND revision=$6-1 AND state IN ('pending','running')
`

type SaveExecutionGraphParams struct {
	State                 string
	MaterializationCursor int
	Inputs                []byte
	Outputs               []byte
	Failure               []byte
	Revision              int64
	RunID                 string
	ID                    string
}

func (q *Queries) SaveExecutionGraph(ctx context.Context, arg SaveExecutionGraphParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveExecutionGraph,
		arg.State,
		arg.MaterializationCursor,
		arg.Inputs,
		arg.Outputs,
		arg.Failure,
		arg.Revision,
		arg.RunID,
		arg.ID,
	)
}

const saveExecutionNode = `-- name: SaveExecutionNode :execresult
INSERT INTO knotra_execution_nodes(run_id,id,graph_id,node_id,address,state,inputs,outputs,failure,
		execution_request,deadline,attempt_number,revision,started_at,finished_at,reason,node_kind,dependency_node_ids,remaining_dependencies,current_request_id)
		VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,NULLIF($20::text,''))
		ON CONFLICT(run_id,id) DO UPDATE SET state=EXCLUDED.state,inputs=EXCLUDED.inputs,outputs=EXCLUDED.outputs,
		failure=EXCLUDED.failure,execution_request=EXCLUDED.execution_request,deadline=EXCLUDED.deadline,current_request_id=EXCLUDED.current_request_id,
		attempt_number=EXCLUDED.attempt_number,revision=EXCLUDED.revision,started_at=EXCLUDED.started_at,
		finished_at=EXCLUDED.finished_at,reason=EXCLUDED.reason
		WHERE knotra_execution_nodes.revision=EXCLUDED.revision-1
		AND knotra_execution_nodes.state NOT IN ('succeeded','skipped','failed','cancelled')
		AND (knotra_execution_nodes.deadline IS NULL OR knotra_execution_nodes.deadline=EXCLUDED.deadline)
`

type SaveExecutionNodeParams struct {
	RunID                 string
	ID                    string
	GraphID               string
	NodeID                string
	Address               string
	State                 string
	Inputs                []byte
	Outputs               []byte
	Failure               []byte
	ExecutionRequest      []byte
	Deadline              *time.Time
	AttemptNumber         int
	Revision              int64
	StartedAt             *time.Time
	FinishedAt            *time.Time
	Reason                string
	NodeKind              string
	DependencyNodeIds     []string
	RemainingDependencies int
	CurrentRequestID      string
}

func (q *Queries) SaveExecutionNode(ctx context.Context, arg SaveExecutionNodeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveExecutionNode,
		arg.RunID,
		arg.ID,
		arg.GraphID,
		arg.NodeID,
		arg.Address,
		arg.State,
		arg.Inputs,
		arg.Outputs,
		arg.Failure,
		arg.ExecutionRequest,
		arg.Deadline,
		arg.AttemptNumber,
		arg.Revision,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Reason,
		arg.NodeKind,
		arg.DependencyNodeIds,
		arg.RemainingDependencies,
		arg.CurrentRequestID,
	)
}

const saveExecutionRequest = `-- name: SaveExecutionRequest :execresult
UPDATE knotra_requests SET status=$3,document=$4
		WHERE run_id=$1 AND id=$2 AND response_id=$5 AND
		((kind='human' AND status='answered' AND $3='accepted') OR (kind='resolution' AND status='resolved' AND $3='resolved'))
`

type SaveExecutionRequestParams struct {
	RunID      string
	ID         string
	Status     string
	Document   []byte
	ResponseID *string
}

func (q *Queries) SaveExecutionRequest(ctx context.Context, arg SaveExecutionRequestParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveExecutionRequest,
		arg.RunID,
		arg.ID,
		arg.Status,
		arg.Document,
		arg.ResponseID,
	)
}

const setGraphCursor = `-- name: SetGraphCursor :execresult
UPDATE knotra_runs SET graph_cursor=$2,state_revision=state_revision+1 WHERE id=$1
`

type SetGraphCursorParams struct {
	ID          string
	GraphCursor string
}

func (q *Queries) SetGraphCursor(ctx context.Context, arg SetGraphCursorParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setGraphCursor, arg.ID, arg.GraphCursor)
}
