// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lease.sql

package db

import (
	"context"
)

const acquireLease = `-- name: AcquireLease :one
SELECT pg_try_advisory_lock(hashtextextended($1,0))
`

func (q *Queries) AcquireLease(ctx context.Context, hashtextextended string) (bool, error) {
	row := q.db.QueryRow(ctx, acquireLease, hashtextextended)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
