// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const currentSchema = `-- name: CurrentSchema :one
SELECT current_schema()::text
`

func (q *Queries) CurrentSchema(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, currentSchema)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const lockRiverMigrations = `-- name: LockRiverMigrations :execresult
SELECT pg_advisory_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockRiverMigrations(ctx context.Context, dollar_1 string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, lockRiverMigrations, dollar_1)
}
