// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const observe = `-- name: Observe :execresult
INSERT INTO knotra_events(run_id,sequence,document) VALUES($1,NULL,$2)
`

type ObserveParams struct {
	RunID    string
	Document []byte
}

func (q *Queries) Observe(ctx context.Context, arg ObserveParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, observe, arg.RunID, arg.Document)
}
