// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const cancelAttempt = `-- name: CancelAttempt :execresult
UPDATE knotra_execution_attempts SET state='cancelled'
				WHERE run_id=$1 AND instance_id=$2 AND number=$3
`

type CancelAttemptParams struct {
	RunID      string
	InstanceID string
	Number     int
}

func (q *Queries) CancelAttempt(ctx context.Context, arg CancelAttemptParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, cancelAttempt, arg.RunID, arg.InstanceID, arg.Number)
}

const hasUnconfirmedOperations = `-- name: HasUnconfirmedOperations :one
SELECT EXISTS(SELECT 1 FROM knotra_operations WHERE run_id=$1 AND instance_id=$2
			AND attempt_number=$3 AND kind IN ('model','tool') AND admitted_at IS NOT NULL AND NOT completed)
`

type HasUnconfirmedOperationsParams struct {
	RunID         string
	InstanceID    *string
	AttemptNumber *int
}

func (q *Queries) HasUnconfirmedOperations(ctx context.Context, arg HasUnconfirmedOperationsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnconfirmedOperations, arg.RunID, arg.InstanceID, arg.AttemptNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockOutcomeAttempt = `-- name: LockOutcomeAttempt :one
SELECT n.state AS node_state,n.attempt_number,n.deadline,a.state AS attempt_state,a.owner,a.ownership_generation,a.outcome_key,a.outcome,(r.plan->>'digest')::text AS plan_digest
		FROM knotra_execution_nodes n JOIN knotra_execution_attempts a ON a.run_id=n.run_id AND a.instance_id=n.id
		JOIN knotra_runs r ON r.id=n.run_id WHERE n.run_id=$1 AND n.id=$2 AND a.number=$3 FOR UPDATE OF n,a
`

type LockOutcomeAttemptParams struct {
	RunID  string
	ID     string
	Number int
}

type LockOutcomeAttemptRow struct {
	NodeState           string
	AttemptNumber       int
	Deadline            *time.Time
	AttemptState        string
	Owner               *string
	OwnershipGeneration int64
	OutcomeKey          *string
	Outcome             []byte
	PlanDigest          string
}

func (q *Queries) LockOutcomeAttempt(ctx context.Context, arg LockOutcomeAttemptParams) (LockOutcomeAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockOutcomeAttempt, arg.RunID, arg.ID, arg.Number)
	var i LockOutcomeAttemptRow
	err := row.Scan(
		&i.NodeState,
		&i.AttemptNumber,
		&i.Deadline,
		&i.AttemptState,
		&i.Owner,
		&i.OwnershipGeneration,
		&i.OutcomeKey,
		&i.Outcome,
		&i.PlanDigest,
	)
	return i, err
}

const outcomeMatches = `-- name: OutcomeMatches :one
SELECT outcome=$1::jsonb FROM knotra_execution_attempts
			WHERE run_id=$2 AND instance_id=$3 AND number=$4
`

type OutcomeMatchesParams struct {
	Outcome    []byte
	RunID      string
	InstanceID string
	Number     int
}

func (q *Queries) OutcomeMatches(ctx context.Context, arg OutcomeMatchesParams) (bool, error) {
	row := q.db.QueryRow(ctx, outcomeMatches,
		arg.Outcome,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const saveOutcomeEvidence = `-- name: SaveOutcomeEvidence :execresult
UPDATE knotra_execution_attempts SET outcome=$4,evidence_key=$5
		WHERE run_id=$1 AND instance_id=$2 AND number=$3
`

type SaveOutcomeEvidenceParams struct {
	RunID       string
	InstanceID  string
	Number      int
	Outcome     []byte
	EvidenceKey *string
}

func (q *Queries) SaveOutcomeEvidence(ctx context.Context, arg SaveOutcomeEvidenceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveOutcomeEvidence,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
		arg.Outcome,
		arg.EvidenceKey,
	)
}

const setAttemptCompleted = `-- name: SetAttemptCompleted :execresult
UPDATE knotra_execution_attempts SET state='completed',result=$4
		WHERE run_id=$1 AND instance_id=$2 AND number=$3
`

type SetAttemptCompletedParams struct {
	RunID      string
	InstanceID string
	Number     int
	Result     []byte
}

func (q *Queries) SetAttemptCompleted(ctx context.Context, arg SetAttemptCompletedParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setAttemptCompleted,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
		arg.Result,
	)
}
