// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owned_operations.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const insertOwnedOperation = `-- name: InsertOwnedOperation :execresult
INSERT INTO knotra_operations(id,run_id,kind,effect,instance_id,attempt_number,worker_id,ownership_generation,admitted_at)
				VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertOwnedOperationParams struct {
	ID                  string
	RunID               string
	Kind                string
	Effect              string
	InstanceID          *string
	AttemptNumber       *int
	WorkerID            *string
	OwnershipGeneration *int64
	AdmittedAt          *time.Time
}

func (q *Queries) InsertOwnedOperation(ctx context.Context, arg InsertOwnedOperationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertOwnedOperation,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.Effect,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.WorkerID,
		arg.OwnershipGeneration,
		arg.AdmittedAt,
	)
}

const lockOperationAdmission = `-- name: LockOperationAdmission :one
SELECT admitted_at FROM knotra_operations WHERE id=$1 AND run_id=$2 AND instance_id=$3
			AND attempt_number=$4 AND worker_id=$5 AND ownership_generation=$6 AND kind=$7 AND NOT completed FOR UPDATE
`

type LockOperationAdmissionParams struct {
	ID                  string
	RunID               string
	InstanceID          *string
	AttemptNumber       *int
	WorkerID            *string
	OwnershipGeneration *int64
	Kind                string
}

func (q *Queries) LockOperationAdmission(ctx context.Context, arg LockOperationAdmissionParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, lockOperationAdmission,
		arg.ID,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.WorkerID,
		arg.OwnershipGeneration,
		arg.Kind,
	)
	var admitted_at *time.Time
	err := row.Scan(&admitted_at)
	return admitted_at, err
}

const lockOperationIntent = `-- name: LockOperationIntent :one
SELECT run_id,kind,effect,instance_id,admitted_at,completed,response
			FROM knotra_operations WHERE id=$1 FOR UPDATE
`

type LockOperationIntentRow struct {
	RunID      string
	Kind       string
	Effect     string
	InstanceID *string
	AdmittedAt *time.Time
	Completed  bool
	Response   []byte
}

func (q *Queries) LockOperationIntent(ctx context.Context, id string) (LockOperationIntentRow, error) {
	row := q.db.QueryRow(ctx, lockOperationIntent, id)
	var i LockOperationIntentRow
	err := row.Scan(
		&i.RunID,
		&i.Kind,
		&i.Effect,
		&i.InstanceID,
		&i.AdmittedAt,
		&i.Completed,
		&i.Response,
	)
	return i, err
}

const lockOperationScopes = `-- name: LockOperationScopes :many
SELECT s.id,s.limits FROM knotra_execution_scopes s JOIN knotra_execution_slots r
			ON r.run_id=s.run_id AND r.scope_id=s.id WHERE r.run_id=$1 AND r.instance_id=$2 AND r.attempt_number=$3
			AND r.ownership_generation=$4 AND r.released_at IS NULL ORDER BY s.id FOR UPDATE OF s
`

type LockOperationScopesParams struct {
	RunID               string
	InstanceID          string
	AttemptNumber       int
	OwnershipGeneration int64
}

type LockOperationScopesRow struct {
	ID     string
	Limits []byte
}

func (q *Queries) LockOperationScopes(ctx context.Context, arg LockOperationScopesParams) ([]LockOperationScopesRow, error) {
	rows, err := q.db.Query(ctx, lockOperationScopes,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.OwnershipGeneration,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockOperationScopesRow{}
	for rows.Next() {
		var i LockOperationScopesRow
		if err := rows.Scan(&i.ID, &i.Limits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnedOperationResponse = `-- name: LockOwnedOperationResponse :one
SELECT completed,response FROM knotra_operations WHERE id=$1 AND run_id=$2 AND instance_id=$3
			AND attempt_number=$4 AND worker_id=$5 AND ownership_generation=$6 AND admitted_at IS NOT NULL FOR UPDATE
`

type LockOwnedOperationResponseParams struct {
	ID                  string
	RunID               string
	InstanceID          *string
	AttemptNumber       *int
	WorkerID            *string
	OwnershipGeneration *int64
}

type LockOwnedOperationResponseRow struct {
	Completed bool
	Response  []byte
}

func (q *Queries) LockOwnedOperationResponse(ctx context.Context, arg LockOwnedOperationResponseParams) (LockOwnedOperationResponseRow, error) {
	row := q.db.QueryRow(ctx, lockOwnedOperationResponse,
		arg.ID,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.WorkerID,
		arg.OwnershipGeneration,
	)
	var i LockOwnedOperationResponseRow
	err := row.Scan(&i.Completed, &i.Response)
	return i, err
}

const setOperationAdmitted = `-- name: SetOperationAdmitted :execresult
UPDATE knotra_operations SET admitted_at=$2 WHERE id=$1
`

type SetOperationAdmittedParams struct {
	ID         string
	AdmittedAt *time.Time
}

func (q *Queries) SetOperationAdmitted(ctx context.Context, arg SetOperationAdmittedParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setOperationAdmitted, arg.ID, arg.AdmittedAt)
}

const setOperationCompleted = `-- name: SetOperationCompleted :execresult
UPDATE knotra_operations SET completed=true,response=$2 WHERE id=$1
`

type SetOperationCompletedParams struct {
	ID       string
	Response []byte
}

func (q *Queries) SetOperationCompleted(ctx context.Context, arg SetOperationCompletedParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setOperationCompleted, arg.ID, arg.Response)
}

const transferPreparedOperation = `-- name: TransferPreparedOperation :execresult
UPDATE knotra_operations SET attempt_number=$2,worker_id=$3,ownership_generation=$4 WHERE id=$1
`

type TransferPreparedOperationParams struct {
	ID                  string
	AttemptNumber       *int
	WorkerID            *string
	OwnershipGeneration *int64
}

func (q *Queries) TransferPreparedOperation(ctx context.Context, arg TransferPreparedOperationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, transferPreparedOperation,
		arg.ID,
		arg.AttemptNumber,
		arg.WorkerID,
		arg.OwnershipGeneration,
	)
}
