// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projections.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const cancelOpenRequests = `-- name: CancelOpenRequests :execresult
UPDATE knotra_requests SET status='cancelled' WHERE run_id=$1 AND status IN ('open','pending')
`

func (q *Queries) CancelOpenRequests(ctx context.Context, runID string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, cancelOpenRequests, runID)
}

const closeRequest = `-- name: CloseRequest :execresult
UPDATE knotra_requests SET status=$2 WHERE id=$1 AND status IN ('open','pending')
`

type CloseRequestParams struct {
	ID     string
	Status string
}

func (q *Queries) CloseRequest(ctx context.Context, arg CloseRequestParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, closeRequest, arg.ID, arg.Status)
}

const completeLegacyOperation = `-- name: CompleteLegacyOperation :execresult
UPDATE knotra_operations SET completed=true,response=$2 WHERE id=$1 AND NOT completed AND worker_id IS NULL
`

type CompleteLegacyOperationParams struct {
	ID       string
	Response []byte
}

func (q *Queries) CompleteLegacyOperation(ctx context.Context, arg CompleteLegacyOperationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, completeLegacyOperation, arg.ID, arg.Response)
}

const eventSequenceExists = `-- name: EventSequenceExists :one
SELECT EXISTS(SELECT 1 FROM knotra_events WHERE run_id=$1 AND sequence=$2)
`

type EventSequenceExistsParams struct {
	RunID    string
	Sequence *int64
}

func (q *Queries) EventSequenceExists(ctx context.Context, arg EventSequenceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, eventSequenceExists, arg.RunID, arg.Sequence)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementBudget = `-- name: IncrementBudget :execresult
INSERT INTO knotra_budgets(run_id,scope,kind,used) VALUES($1,$2,$3,1) ON CONFLICT(run_id,scope,kind) DO UPDATE SET used=knotra_budgets.used+1
`

type IncrementBudgetParams struct {
	RunID string
	Scope string
	Kind  string
}

func (q *Queries) IncrementBudget(ctx context.Context, arg IncrementBudgetParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, incrementBudget, arg.RunID, arg.Scope, arg.Kind)
}

const insertExecutionEvent = `-- name: InsertExecutionEvent :execresult
INSERT INTO knotra_events(run_id,sequence,document) VALUES($1,$2,$3)
`

type InsertExecutionEventParams struct {
	RunID    string
	Sequence *int64
	Document []byte
}

func (q *Queries) InsertExecutionEvent(ctx context.Context, arg InsertExecutionEventParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertExecutionEvent, arg.RunID, arg.Sequence, arg.Document)
}

const insertLegacyOperation = `-- name: InsertLegacyOperation :execresult
INSERT INTO knotra_operations(id,run_id,kind,effect)
		 SELECT $1,r.id,$2,$3 FROM knotra_runs r WHERE r.id=$4 AND backend='temporal' ON CONFLICT DO NOTHING
`

type InsertLegacyOperationParams struct {
	ID     string
	Kind   string
	Effect string
	RunID  string
}

func (q *Queries) InsertLegacyOperation(ctx context.Context, arg InsertLegacyOperationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertLegacyOperation,
		arg.ID,
		arg.Kind,
		arg.Effect,
		arg.RunID,
	)
}

const listHumanRequests = `-- name: ListHumanRequests :many
WITH candidates AS (
    SELECT id,octet_length(document::text) AS bytes
    FROM knotra_requests
    WHERE kind='human' AND ($2::text='' OR id<$2)
    ORDER BY id DESC
    LIMIT 101
), page AS (
    SELECT id,row_number() OVER (ORDER BY id DESC) AS position,
        COALESCE(sum(bytes) OVER (ORDER BY id DESC ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING),0) AS preceding_bytes
    FROM candidates
)
SELECT d.document,d.status,d.created_at
FROM knotra_requests d JOIN page p ON p.id=d.id
WHERE p.position<=2 OR p.preceding_bytes<=$1::bigint
ORDER BY d.id DESC
`

type ListHumanRequestsParams struct {
	MaxBytes int64
	Cursor   string
}

type ListHumanRequestsRow struct {
	Document  []byte
	Status    string
	CreatedAt time.Time
}

// Bound raw documents before sqlc materializes them; keep one cursor marker.
func (q *Queries) ListHumanRequests(ctx context.Context, arg ListHumanRequestsParams) ([]ListHumanRequestsRow, error) {
	rows, err := q.db.Query(ctx, listHumanRequests, arg.MaxBytes, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHumanRequestsRow{}
	for rows.Next() {
		var i ListHumanRequestsRow
		if err := rows.Scan(&i.Document, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHumanAnswer = `-- name: LockHumanAnswer :one
SELECT status,response_id,response,accepted_at FROM knotra_requests WHERE id=$1 AND run_id=$2 FOR UPDATE
`

type LockHumanAnswerParams struct {
	ID    string
	RunID string
}

type LockHumanAnswerRow struct {
	Status     string
	ResponseID *string
	Response   []byte
	AcceptedAt *time.Time
}

func (q *Queries) LockHumanAnswer(ctx context.Context, arg LockHumanAnswerParams) (LockHumanAnswerRow, error) {
	row := q.db.QueryRow(ctx, lockHumanAnswer, arg.ID, arg.RunID)
	var i LockHumanAnswerRow
	err := row.Scan(
		&i.Status,
		&i.ResponseID,
		&i.Response,
		&i.AcceptedAt,
	)
	return i, err
}

const lockRunProjection = `-- name: LockRunProjection :one
SELECT document,sequence FROM knotra_runs WHERE id=$1 FOR UPDATE
`

type LockRunProjectionRow struct {
	Document []byte
	Sequence int64
}

func (q *Queries) LockRunProjection(ctx context.Context, id string) (LockRunProjectionRow, error) {
	row := q.db.QueryRow(ctx, lockRunProjection, id)
	var i LockRunProjectionRow
	err := row.Scan(&i.Document, &i.Sequence)
	return i, err
}

const lockTransactionKey = `-- name: LockTransactionKey :execresult
SELECT pg_advisory_xact_lock(hashtextextended($1,0))
`

func (q *Queries) LockTransactionKey(ctx context.Context, hashtextextended string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, lockTransactionKey, hashtextextended)
}

const publishArtifact = `-- name: PublishArtifact :execresult
UPDATE knotra_artifacts SET published=true WHERE id=$1 AND document->'origin'->>'runId'=$2::text
`

type PublishArtifactParams struct {
	ID          string
	OriginRunID string
}

func (q *Queries) PublishArtifact(ctx context.Context, arg PublishArtifactParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, publishArtifact, arg.ID, arg.OriginRunID)
}

const readBudgetUsed = `-- name: ReadBudgetUsed :one
SELECT used FROM knotra_budgets WHERE run_id=$1 AND scope=$2 AND kind=$3
`

type ReadBudgetUsedParams struct {
	RunID string
	Scope string
	Kind  string
}

func (q *Queries) ReadBudgetUsed(ctx context.Context, arg ReadBudgetUsedParams) (int64, error) {
	row := q.db.QueryRow(ctx, readBudgetUsed, arg.RunID, arg.Scope, arg.Kind)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const readLegacyOperation = `-- name: ReadLegacyOperation :one
SELECT o.completed,o.response FROM knotra_operations o JOIN knotra_runs r ON r.id=o.run_id
		WHERE o.id=$1 AND o.run_id=$2 AND r.backend='temporal'
`

type ReadLegacyOperationParams struct {
	ID    string
	RunID string
}

type ReadLegacyOperationRow struct {
	Completed bool
	Response  []byte
}

func (q *Queries) ReadLegacyOperation(ctx context.Context, arg ReadLegacyOperationParams) (ReadLegacyOperationRow, error) {
	row := q.db.QueryRow(ctx, readLegacyOperation, arg.ID, arg.RunID)
	var i ReadLegacyOperationRow
	err := row.Scan(&i.Completed, &i.Response)
	return i, err
}

const readLegacyOperationResponse = `-- name: ReadLegacyOperationResponse :one
SELECT response FROM knotra_operations WHERE id=$1 AND completed AND worker_id IS NULL
`

func (q *Queries) ReadLegacyOperationResponse(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, readLegacyOperationResponse, id)
	var response []byte
	err := row.Scan(&response)
	return response, err
}

const readRequest = `-- name: ReadRequest :one
SELECT document,status FROM knotra_requests WHERE id=$1
`

type ReadRequestRow struct {
	Document []byte
	Status   string
}

func (q *Queries) ReadRequest(ctx context.Context, id string) (ReadRequestRow, error) {
	row := q.db.QueryRow(ctx, readRequest, id)
	var i ReadRequestRow
	err := row.Scan(&i.Document, &i.Status)
	return i, err
}

const updateRunProjection = `-- name: UpdateRunProjection :execresult
UPDATE knotra_runs SET document=$2,sequence=$3 WHERE id=$1
`

type UpdateRunProjectionParams struct {
	ID       string
	Document []byte
	Sequence int64
}

func (q *Queries) UpdateRunProjection(ctx context.Context, arg UpdateRunProjectionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateRunProjection, arg.ID, arg.Document, arg.Sequence)
}

const upsertInstanceProjection = `-- name: UpsertInstanceProjection :execresult
INSERT INTO knotra_instances(run_id,id,sequence,document) VALUES($1,$2,$3,$4) ON CONFLICT(run_id,id) DO UPDATE SET sequence=EXCLUDED.sequence,document=EXCLUDED.document WHERE knotra_instances.sequence<EXCLUDED.sequence
`

type UpsertInstanceProjectionParams struct {
	RunID    string
	ID       string
	Sequence int64
	Document []byte
}

func (q *Queries) UpsertInstanceProjection(ctx context.Context, arg UpsertInstanceProjectionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertInstanceProjection,
		arg.RunID,
		arg.ID,
		arg.Sequence,
		arg.Document,
	)
}

const upsertRequest = `-- name: UpsertRequest :execresult
INSERT INTO knotra_requests(id,run_id,kind,status,document) VALUES($1,$2,$3,$4,$5)
 ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,document=EXCLUDED.document
 WHERE knotra_requests.status IN ('open','pending') AND EXCLUDED.status NOT IN ('open','pending')
`

type UpsertRequestParams struct {
	ID       string
	RunID    string
	Kind     string
	Status   string
	Document []byte
}

func (q *Queries) UpsertRequest(ctx context.Context, arg UpsertRequestParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertRequest,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.Status,
		arg.Document,
	)
}
