// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const bindWorkerDeliveryClient = `-- name: BindWorkerDeliveryClient :execresult
UPDATE knotra_workers SET delivery_client_id=$3
WHERE id=$1 AND engine_id=$2 AND (delivery_client_id IS NULL OR delivery_client_id=$3)
`

type BindWorkerDeliveryClientParams struct {
	ID               string
	EngineID         string
	DeliveryClientID *string
}

func (q *Queries) BindWorkerDeliveryClient(ctx context.Context, arg BindWorkerDeliveryClientParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, bindWorkerDeliveryClient, arg.ID, arg.EngineID, arg.DeliveryClientID)
}

const firstUnconfirmedOperation = `-- name: FirstUnconfirmedOperation :one
SELECT id FROM knotra_operations WHERE run_id=$1 AND instance_id=$2 AND attempt_number=$3
    AND admitted_at IS NOT NULL AND NOT completed
ORDER BY created_at,id LIMIT 1
`

type FirstUnconfirmedOperationParams struct {
	RunID         string
	InstanceID    *string
	AttemptNumber *int
}

func (q *Queries) FirstUnconfirmedOperation(ctx context.Context, arg FirstUnconfirmedOperationParams) (string, error) {
	row := q.db.QueryRow(ctx, firstUnconfirmedOperation, arg.RunID, arg.InstanceID, arg.AttemptNumber)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listDeliveryRepairRuns = `-- name: ListDeliveryRepairRuns :many
SELECT r.id FROM knotra_runs r
WHERE r.backend='river' AND r.id>$1::text
    AND r.document->>'status' NOT IN ('succeeded','failed','cancelled')
    AND (r.wake_generation>r.applied_generation OR EXISTS(
        SELECT 1 FROM knotra_execution_attempts a WHERE a.run_id=r.id AND a.state='ready'))
ORDER BY r.id LIMIT 64
`

func (q *Queries) ListDeliveryRepairRuns(ctx context.Context, cursor string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeliveryRepairRuns, cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLostAttempt = `-- name: LockLostAttempt :one
SELECT a.state,a.owner,a.ownership_generation,a.lease_expires_at,a.outcome_key,a.outcome,
    n.state AS node_state,n.attempt_number,n.execution_request
FROM knotra_execution_nodes n JOIN knotra_execution_attempts a
    ON a.run_id=n.run_id AND a.instance_id=n.id
WHERE a.run_id=$1 AND a.instance_id=$2 AND a.number=$3
FOR UPDATE OF n,a
`

type LockLostAttemptParams struct {
	RunID      string
	InstanceID string
	Number     int
}

type LockLostAttemptRow struct {
	State               string
	Owner               *string
	OwnershipGeneration int64
	LeaseExpiresAt      *time.Time
	OutcomeKey          *string
	Outcome             []byte
	NodeState           string
	AttemptNumber       int
	ExecutionRequest    []byte
}

func (q *Queries) LockLostAttempt(ctx context.Context, arg LockLostAttemptParams) (LockLostAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockLostAttempt, arg.RunID, arg.InstanceID, arg.Number)
	var i LockLostAttemptRow
	err := row.Scan(
		&i.State,
		&i.Owner,
		&i.OwnershipGeneration,
		&i.LeaseExpiresAt,
		&i.OutcomeKey,
		&i.Outcome,
		&i.NodeState,
		&i.AttemptNumber,
		&i.ExecutionRequest,
	)
	return i, err
}

const readDeliveryWorkerHeartbeat = `-- name: ReadDeliveryWorkerHeartbeat :one
SELECT heartbeat_at FROM knotra_workers WHERE engine_id=$1 AND delivery_client_id=$2
`

type ReadDeliveryWorkerHeartbeatParams struct {
	EngineID         string
	DeliveryClientID *string
}

func (q *Queries) ReadDeliveryWorkerHeartbeat(ctx context.Context, arg ReadDeliveryWorkerHeartbeatParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, readDeliveryWorkerHeartbeat, arg.EngineID, arg.DeliveryClientID)
	var heartbeat_at time.Time
	err := row.Scan(&heartbeat_at)
	return heartbeat_at, err
}

const readReadyDeliveries = `-- name: ReadReadyDeliveries :many
SELECT a.instance_id,a.number,a.dispatch_generation
FROM knotra_execution_attempts a JOIN knotra_execution_nodes n ON n.run_id=a.run_id AND n.id=a.instance_id
WHERE a.run_id=$1 AND a.state='ready' AND n.state='ready' AND a.number=n.attempt_number
    AND a.instance_id>$2::text AND n.deadline>$3::timestamptz
    AND NOT EXISTS(
        SELECT 1 FROM jsonb_array_elements(n.execution_request->'scopes') scope
        LEFT JOIN knotra_execution_scopes s ON s.run_id=a.run_id AND s.id=scope->>'id'
        WHERE s.id IS NULL OR s.active_attempts>=(s.limits->>'maxConcurrentNodes')::integer
    )
ORDER BY a.instance_id LIMIT 64
`

type ReadReadyDeliveriesParams struct {
	RunID  string
	Cursor string
	Now    time.Time
}

type ReadReadyDeliveriesRow struct {
	InstanceID         string
	Number             int
	DispatchGeneration int64
}

func (q *Queries) ReadReadyDeliveries(ctx context.Context, arg ReadReadyDeliveriesParams) ([]ReadReadyDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, readReadyDeliveries, arg.RunID, arg.Cursor, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadReadyDeliveriesRow{}
	for rows.Next() {
		var i ReadReadyDeliveriesRow
		if err := rows.Scan(&i.InstanceID, &i.Number, &i.DispatchGeneration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeliveryCursor = `-- name: SetDeliveryCursor :execresult
UPDATE knotra_runs SET delivery_cursor=$2,state_revision=state_revision+1 WHERE id=$1
`

type SetDeliveryCursorParams struct {
	ID             string
	DeliveryCursor string
}

func (q *Queries) SetDeliveryCursor(ctx context.Context, arg SetDeliveryCursorParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setDeliveryCursor, arg.ID, arg.DeliveryCursor)
}

const setLostAttempt = `-- name: SetLostAttempt :execresult
UPDATE knotra_execution_attempts SET state=$1,result=$2,failure=$3
WHERE run_id=$4 AND instance_id=$5 AND number=$6
    AND state='claimed'
`

type SetLostAttemptParams struct {
	State      string
	Result     []byte
	Failure    []byte
	RunID      string
	InstanceID string
	Number     int
}

func (q *Queries) SetLostAttempt(ctx context.Context, arg SetLostAttemptParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setLostAttempt,
		arg.State,
		arg.Result,
		arg.Failure,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
	)
}
