// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const acceptHumanAnswer = `-- name: AcceptHumanAnswer :execresult
UPDATE knotra_requests SET status='answered',response_id=$2,response=$3,accepted_at=$4 WHERE id=$1
`

type AcceptHumanAnswerParams struct {
	ID         string
	ResponseID *string
	Response   []byte
	AcceptedAt *time.Time
}

func (q *Queries) AcceptHumanAnswer(ctx context.Context, arg AcceptHumanAnswerParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, acceptHumanAnswer,
		arg.ID,
		arg.ResponseID,
		arg.Response,
		arg.AcceptedAt,
	)
}

const acceptResolution = `-- name: AcceptResolution :execresult
UPDATE knotra_requests SET status='resolved',response_id=$2,response=$3,accepted_at=$4 WHERE id=$1
`

type AcceptResolutionParams struct {
	ID         string
	ResponseID *string
	Response   []byte
	AcceptedAt *time.Time
}

func (q *Queries) AcceptResolution(ctx context.Context, arg AcceptResolutionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, acceptResolution,
		arg.ID,
		arg.ResponseID,
		arg.Response,
		arg.AcceptedAt,
	)
}

const lockRequest = `-- name: LockRequest :one
SELECT document,status FROM knotra_requests WHERE id=$1 FOR UPDATE
`

type LockRequestRow struct {
	Document []byte
	Status   string
}

func (q *Queries) LockRequest(ctx context.Context, id string) (LockRequestRow, error) {
	row := q.db.QueryRow(ctx, lockRequest, id)
	var i LockRequestRow
	err := row.Scan(&i.Document, &i.Status)
	return i, err
}

const lockResolutionAnswer = `-- name: LockResolutionAnswer :one
SELECT status,response,accepted_at FROM knotra_requests WHERE id=$1 AND run_id=$2 AND kind='resolution' FOR UPDATE
`

type LockResolutionAnswerParams struct {
	ID    string
	RunID string
}

type LockResolutionAnswerRow struct {
	Status     string
	Response   []byte
	AcceptedAt *time.Time
}

func (q *Queries) LockResolutionAnswer(ctx context.Context, arg LockResolutionAnswerParams) (LockResolutionAnswerRow, error) {
	row := q.db.QueryRow(ctx, lockResolutionAnswer, arg.ID, arg.RunID)
	var i LockResolutionAnswerRow
	err := row.Scan(&i.Status, &i.Response, &i.AcceptedAt)
	return i, err
}

const lockResolutionRequest = `-- name: LockResolutionRequest :one
SELECT document,status FROM knotra_requests WHERE run_id=$1 AND kind='resolution' AND document->>'instanceId'=$2::text ORDER BY created_at DESC LIMIT 1 FOR UPDATE
`

type LockResolutionRequestParams struct {
	RunID      string
	InstanceID string
}

type LockResolutionRequestRow struct {
	Document []byte
	Status   string
}

func (q *Queries) LockResolutionRequest(ctx context.Context, arg LockResolutionRequestParams) (LockResolutionRequestRow, error) {
	row := q.db.QueryRow(ctx, lockResolutionRequest, arg.RunID, arg.InstanceID)
	var i LockResolutionRequestRow
	err := row.Scan(&i.Document, &i.Status)
	return i, err
}

const lockRunCommand = `-- name: LockRunCommand :one
SELECT document,cancel_requested FROM knotra_runs WHERE id=$1 FOR UPDATE
`

type LockRunCommandRow struct {
	Document        []byte
	CancelRequested bool
}

func (q *Queries) LockRunCommand(ctx context.Context, id string) (LockRunCommandRow, error) {
	row := q.db.QueryRow(ctx, lockRunCommand, id)
	var i LockRunCommandRow
	err := row.Scan(&i.Document, &i.CancelRequested)
	return i, err
}

const readRequestRunID = `-- name: ReadRequestRunID :one
SELECT run_id FROM knotra_requests WHERE id=$1
`

func (q *Queries) ReadRequestRunID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, readRequestRunID, id)
	var run_id string
	err := row.Scan(&run_id)
	return run_id, err
}

const setRunCancelled = `-- name: SetRunCancelled :execresult
UPDATE knotra_runs SET cancel_requested=true WHERE id=$1
`

func (q *Queries) SetRunCancelled(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setRunCancelled, id)
}
