// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const bumpResourceCleanupDelivery = `-- name: BumpResourceCleanupDelivery :one
UPDATE knotra_resources SET cleanup_generation=cleanup_generation+1
WHERE id=$1 AND state='cleaning' RETURNING cleanup_generation
`

func (q *Queries) BumpResourceCleanupDelivery(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, bumpResourceCleanupDelivery, id)
	var cleanup_generation int64
	err := row.Scan(&cleanup_generation)
	return cleanup_generation, err
}

const claimResourceCleanup = `-- name: ClaimResourceCleanup :execresult
UPDATE knotra_resources SET state='cleaning' WHERE id=$1
`

func (q *Queries) ClaimResourceCleanup(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, claimResourceCleanup, id)
}

const closeCleanedResource = `-- name: CloseCleanedResource :execresult
UPDATE knotra_resources SET state='closed',closed_at=COALESCE(closed_at,clock_timestamp())
WHERE id=$1 AND engine_id=$2 AND host_id=$3 AND worker_id=$4
    AND ownership_generation=$5 AND cleanup_generation=$6 AND state='cleaning'
`

type CloseCleanedResourceParams struct {
	ID                  string
	EngineID            string
	HostID              string
	WorkerID            string
	OwnershipGeneration int64
	CleanupGeneration   int64
}

func (q *Queries) CloseCleanedResource(ctx context.Context, arg CloseCleanedResourceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, closeCleanedResource,
		arg.ID,
		arg.EngineID,
		arg.HostID,
		arg.WorkerID,
		arg.OwnershipGeneration,
		arg.CleanupGeneration,
	)
}

const closeOwnedResource = `-- name: CloseOwnedResource :execresult
UPDATE knotra_resources SET state='closed',closed_at=COALESCE(closed_at,clock_timestamp())
WHERE id=$1 AND engine_id=$2 AND run_id=$3 AND instance_id=$4 AND attempt_number=$5
    AND worker_id=$6 AND ownership_generation=$7
`

type CloseOwnedResourceParams struct {
	ID                  string
	EngineID            string
	RunID               string
	InstanceID          string
	AttemptNumber       int
	WorkerID            string
	OwnershipGeneration int64
}

func (q *Queries) CloseOwnedResource(ctx context.Context, arg CloseOwnedResourceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, closeOwnedResource,
		arg.ID,
		arg.EngineID,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.WorkerID,
		arg.OwnershipGeneration,
	)
}

const insertOwnedResource = `-- name: InsertOwnedResource :execresult
INSERT INTO knotra_resources(id,engine_id,host_id,run_id,instance_id,attempt_number,worker_id,ownership_generation,kind,lifetime)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertOwnedResourceParams struct {
	ID                  string
	EngineID            string
	HostID              string
	RunID               string
	InstanceID          string
	AttemptNumber       int
	WorkerID            string
	OwnershipGeneration int64
	Kind                string
	Lifetime            string
}

func (q *Queries) InsertOwnedResource(ctx context.Context, arg InsertOwnedResourceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertOwnedResource,
		arg.ID,
		arg.EngineID,
		arg.HostID,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.WorkerID,
		arg.OwnershipGeneration,
		arg.Kind,
		arg.Lifetime,
	)
}

const lockResourceCleanup = `-- name: LockResourceCleanup :one
SELECT r.engine_id,r.host_id,r.run_id,r.instance_id,r.attempt_number,r.worker_id,
    r.ownership_generation,r.cleanup_generation,r.kind,r.lifetime,r.state,r.closed_at,w.heartbeat_at,a.state AS attempt_state,
    a.lease_expires_at,r.mcp_session
FROM knotra_resources r JOIN knotra_workers w ON w.id=r.worker_id
JOIN knotra_execution_attempts a ON a.run_id=r.run_id AND a.instance_id=r.instance_id AND a.number=r.attempt_number
WHERE r.id=$1 AND r.engine_id=$2 FOR UPDATE OF r,w
`

type LockResourceCleanupParams struct {
	ID       string
	EngineID string
}

type LockResourceCleanupRow struct {
	EngineID            string
	HostID              string
	RunID               string
	InstanceID          string
	AttemptNumber       int
	WorkerID            string
	OwnershipGeneration int64
	CleanupGeneration   int64
	Kind                string
	Lifetime            string
	State               string
	ClosedAt            *time.Time
	HeartbeatAt         time.Time
	AttemptState        string
	LeaseExpiresAt      *time.Time
	McpSession          []byte
}

func (q *Queries) LockResourceCleanup(ctx context.Context, arg LockResourceCleanupParams) (LockResourceCleanupRow, error) {
	row := q.db.QueryRow(ctx, lockResourceCleanup, arg.ID, arg.EngineID)
	var i LockResourceCleanupRow
	err := row.Scan(
		&i.EngineID,
		&i.HostID,
		&i.RunID,
		&i.InstanceID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.OwnershipGeneration,
		&i.CleanupGeneration,
		&i.Kind,
		&i.Lifetime,
		&i.State,
		&i.ClosedAt,
		&i.HeartbeatAt,
		&i.AttemptState,
		&i.LeaseExpiresAt,
		&i.McpSession,
	)
	return i, err
}

const readResourceCleanupCandidates = `-- name: ReadResourceCleanupCandidates :many
SELECT id,worker_id,ownership_generation
FROM knotra_resources
WHERE engine_id=$1 AND host_id=$2 AND state<>'closed' AND id>$3
ORDER BY id LIMIT 64
`

type ReadResourceCleanupCandidatesParams struct {
	EngineID string
	HostID   string
	Cursor   string
}

type ReadResourceCleanupCandidatesRow struct {
	ID                  string
	WorkerID            string
	OwnershipGeneration int64
}

func (q *Queries) ReadResourceCleanupCandidates(ctx context.Context, arg ReadResourceCleanupCandidatesParams) ([]ReadResourceCleanupCandidatesRow, error) {
	rows, err := q.db.Query(ctx, readResourceCleanupCandidates, arg.EngineID, arg.HostID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadResourceCleanupCandidatesRow{}
	for rows.Next() {
		var i ReadResourceCleanupCandidatesRow
		if err := rows.Scan(&i.ID, &i.WorkerID, &i.OwnershipGeneration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readResourceHost = `-- name: ReadResourceHost :one
SELECT host_id FROM knotra_workers WHERE id=$1 AND engine_id=$2
`

type ReadResourceHostParams struct {
	ID       string
	EngineID string
}

func (q *Queries) ReadResourceHost(ctx context.Context, arg ReadResourceHostParams) (string, error) {
	row := q.db.QueryRow(ctx, readResourceHost, arg.ID, arg.EngineID)
	var host_id string
	err := row.Scan(&host_id)
	return host_id, err
}

const readResourceIdentity = `-- name: ReadResourceIdentity :one
SELECT run_id FROM knotra_resources WHERE id=$1 AND engine_id=$2
`

type ReadResourceIdentityParams struct {
	ID       string
	EngineID string
}

func (q *Queries) ReadResourceIdentity(ctx context.Context, arg ReadResourceIdentityParams) (string, error) {
	row := q.db.QueryRow(ctx, readResourceIdentity, arg.ID, arg.EngineID)
	var run_id string
	err := row.Scan(&run_id)
	return run_id, err
}

const recordOwnedMCPSession = `-- name: RecordOwnedMCPSession :execresult
UPDATE knotra_resources SET mcp_session=$8::jsonb
WHERE id=$1 AND engine_id=$2 AND run_id=$3 AND instance_id=$4 AND attempt_number=$5
    AND worker_id=$6 AND ownership_generation=$7 AND kind='mcp_http'
    AND (mcp_session IS NULL OR mcp_session=$8::jsonb)
`

type RecordOwnedMCPSessionParams struct {
	ID                  string
	EngineID            string
	RunID               string
	InstanceID          string
	AttemptNumber       int
	WorkerID            string
	OwnershipGeneration int64
	McpSession          []byte
}

func (q *Queries) RecordOwnedMCPSession(ctx context.Context, arg RecordOwnedMCPSessionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, recordOwnedMCPSession,
		arg.ID,
		arg.EngineID,
		arg.RunID,
		arg.InstanceID,
		arg.AttemptNumber,
		arg.WorkerID,
		arg.OwnershipGeneration,
		arg.McpSession,
	)
}
