// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const clearAttemptDispatch = `-- name: ClearAttemptDispatch :execresult
UPDATE knotra_execution_attempts SET dispatch_pending=false
			WHERE run_id=$1 AND instance_id=$2 AND number=$3
`

type ClearAttemptDispatchParams struct {
	RunID      string
	InstanceID string
	Number     int
}

func (q *Queries) ClearAttemptDispatch(ctx context.Context, arg ClearAttemptDispatchParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, clearAttemptDispatch, arg.RunID, arg.InstanceID, arg.Number)
}

const consumeDueTimers = `-- name: ConsumeDueTimers :execresult
WITH due AS (
    SELECT id,generation FROM knotra_execution_timers
    WHERE run_id=$1 AND consumed_at IS NULL AND due_at<=$2
    ORDER BY due_at,id,generation LIMIT 64 FOR UPDATE SKIP LOCKED
)
UPDATE knotra_execution_timers t SET consumed_at=$2 FROM due
WHERE t.run_id=$1 AND t.id=due.id AND t.generation=due.generation
`

type ConsumeDueTimersParams struct {
	RunID      string
	ConsumedAt *time.Time
}

func (q *Queries) ConsumeDueTimers(ctx context.Context, arg ConsumeDueTimersParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, consumeDueTimers, arg.RunID, arg.ConsumedAt)
}

const insertExecutionTimer = `-- name: InsertExecutionTimer :execresult
INSERT INTO knotra_execution_timers(run_id,id,generation,instance_id,kind,due_at)
			VALUES($1,$2,$3,$4,$5,$6)
`

type InsertExecutionTimerParams struct {
	RunID      string
	ID         string
	Generation int64
	InstanceID *string
	Kind       string
	DueAt      time.Time
}

func (q *Queries) InsertExecutionTimer(ctx context.Context, arg InsertExecutionTimerParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertExecutionTimer,
		arg.RunID,
		arg.ID,
		arg.Generation,
		arg.InstanceID,
		arg.Kind,
		arg.DueAt,
	)
}

const insertNodeDeadline = `-- name: InsertNodeDeadline :execresult
INSERT INTO knotra_execution_timers(run_id,id,generation,instance_id,kind,due_at)
				VALUES($1,$2,1,$3,'node_deadline',$4) ON CONFLICT DO NOTHING
`

type InsertNodeDeadlineParams struct {
	RunID      string
	ID         string
	InstanceID *string
	DueAt      time.Time
}

func (q *Queries) InsertNodeDeadline(ctx context.Context, arg InsertNodeDeadlineParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertNodeDeadline,
		arg.RunID,
		arg.ID,
		arg.InstanceID,
		arg.DueAt,
	)
}

const listDueTimerRuns = `-- name: ListDueTimerRuns :many
SELECT DISTINCT run_id FROM knotra_execution_timers
		WHERE consumed_at IS NULL AND due_at<=clock_timestamp() ORDER BY run_id LIMIT 64
`

func (q *Queries) ListDueTimerRuns(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDueTimerRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var run_id string
		if err := rows.Scan(&run_id); err != nil {
			return nil, err
		}
		items = append(items, run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredOutcomeAttempts = `-- name: ListExpiredOutcomeAttempts :many
SELECT run_id,instance_id,number,outcome_key,owner,ownership_generation,state FROM knotra_execution_attempts
		WHERE outcome IS NULL AND owner IS NOT NULL AND lease_expires_at<=clock_timestamp()
		AND outcome_key>$1 ORDER BY outcome_key LIMIT 64
`

type ListExpiredOutcomeAttemptsRow struct {
	RunID               string
	InstanceID          string
	Number              int
	OutcomeKey          *string
	Owner               *string
	OwnershipGeneration int64
	State               string
}

// Fenced attempts can receive an envelope after their unknown/stop decision.
// Import evidence without reopening their already decided graph transition.
func (q *Queries) ListExpiredOutcomeAttempts(ctx context.Context, outcomeKey *string) ([]ListExpiredOutcomeAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredOutcomeAttempts, outcomeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredOutcomeAttemptsRow{}
	for rows.Next() {
		var i ListExpiredOutcomeAttemptsRow
		if err := rows.Scan(
			&i.RunID,
			&i.InstanceID,
			&i.Number,
			&i.OutcomeKey,
			&i.Owner,
			&i.OwnershipGeneration,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maximumActiveExecutionDurationMicros = `-- name: MaximumActiveExecutionDurationMicros :one
SELECT COALESCE(max((extract(epoch FROM (execution_deadline-admitted_at))*1000000)::bigint),0)::bigint
FROM knotra_runs WHERE backend='river' AND document->>'status' NOT IN ('succeeded','failed','cancelled','skipped')
`

func (q *Queries) MaximumActiveExecutionDurationMicros(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maximumActiveExecutionDurationMicros)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pauseRunAdmission = `-- name: PauseRunAdmission :execresult
UPDATE knotra_runs SET admission_paused=true WHERE id=$1
`

func (q *Queries) PauseRunAdmission(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, pauseRunAdmission, id)
}

const requiredExecutionBackends = `-- name: RequiredExecutionBackends :many
SELECT DISTINCT backend FROM knotra_runs
WHERE backend='river' OR document->>'status' NOT IN ('succeeded','failed','cancelled','skipped')
UNION
SELECT 'temporal'::text WHERE EXISTS(SELECT 1 FROM knotra_outbox WHERE sent_at IS NULL)
ORDER BY backend
`

// Retained River state may still require outcome/resource cleanup after a run
// terminates. Temporal is needed only for live runs or undelivered commands.
func (q *Queries) RequiredExecutionBackends(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, requiredExecutionBackends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var backend string
		if err := rows.Scan(&backend); err != nil {
			return nil, err
		}
		items = append(items, backend)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveNodeInstances = `-- name: ReserveNodeInstances :execresult
UPDATE knotra_execution_scopes SET materialized_instances=materialized_instances+$3
				WHERE run_id=$1 AND id=$2 AND materialized_instances+$3<=(limits->>'maxNodeInstances')::integer
`

type ReserveNodeInstancesParams struct {
	RunID                 string
	ID                    string
	MaterializedInstances int
}

func (q *Queries) ReserveNodeInstances(ctx context.Context, arg ReserveNodeInstancesParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, reserveNodeInstances, arg.RunID, arg.ID, arg.MaterializedInstances)
}

const resumeRunAdmission = `-- name: ResumeRunAdmission :execresult
UPDATE knotra_runs SET admission_paused=false WHERE id=$1
`

func (q *Queries) ResumeRunAdmission(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, resumeRunAdmission, id)
}

const setAttemptDispatchGeneration = `-- name: SetAttemptDispatchGeneration :execresult
UPDATE knotra_execution_attempts SET dispatch_generation=$4,dispatch_pending=false
			WHERE run_id=$1 AND instance_id=$2 AND number=$3
`

type SetAttemptDispatchGenerationParams struct {
	RunID              string
	InstanceID         string
	Number             int
	DispatchGeneration int64
}

func (q *Queries) SetAttemptDispatchGeneration(ctx context.Context, arg SetAttemptDispatchGenerationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setAttemptDispatchGeneration,
		arg.RunID,
		arg.InstanceID,
		arg.Number,
		arg.DispatchGeneration,
	)
}

const setRunStopCause = `-- name: SetRunStopCause :execresult
UPDATE knotra_runs SET stop_cause=$2 WHERE id=$1
`

type SetRunStopCauseParams struct {
	ID        string
	StopCause []byte
}

func (q *Queries) SetRunStopCause(ctx context.Context, arg SetRunStopCauseParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setRunStopCause, arg.ID, arg.StopCause)
}
