// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const enqueue = `-- name: Enqueue :execresult
INSERT INTO knotra_outbox(run_id,kind,payload) VALUES($1,$2,$3)
`

type EnqueueParams struct {
	RunID   string
	Kind    string
	Payload []byte
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, enqueue, arg.RunID, arg.Kind, arg.Payload)
}

const eventIDExists = `-- name: EventIDExists :one
SELECT EXISTS(SELECT 1 FROM knotra_events WHERE run_id=$1 AND id=$2)
`

type EventIDExistsParams struct {
	RunID string
	ID    int64
}

func (q *Queries) EventIDExists(ctx context.Context, arg EventIDExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, eventIDExists, arg.RunID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertCommandReceipt = `-- name: InsertCommandReceipt :execresult
INSERT INTO knotra_commands(principal,id,route,digest,status,response) VALUES($1,$2,$3,$4,$5,$6)
`

type InsertCommandReceiptParams struct {
	Principal string
	ID        string
	Route     string
	Digest    string
	Status    int
	Response  []byte
}

func (q *Queries) InsertCommandReceipt(ctx context.Context, arg InsertCommandReceiptParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertCommandReceipt,
		arg.Principal,
		arg.ID,
		arg.Route,
		arg.Digest,
		arg.Status,
		arg.Response,
	)
}

const insertEngineID = `-- name: InsertEngineID :execresult
INSERT INTO knotra_settings(key,value) VALUES ('engine_id',$1) ON CONFLICT DO NOTHING
`

func (q *Queries) InsertEngineID(ctx context.Context, value string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertEngineID, value)
}

const insertRun = `-- name: InsertRun :execresult
INSERT INTO knotra_runs(id,definition_id,document,plan,inputs) VALUES($1,$2,$3,$4,$5)
`

type InsertRunParams struct {
	ID           string
	DefinitionID string
	Document     []byte
	Plan         []byte
	Inputs       []byte
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertRun,
		arg.ID,
		arg.DefinitionID,
		arg.Document,
		arg.Plan,
		arg.Inputs,
	)
}

const listDefinitions = `-- name: ListDefinitions :many
WITH candidates AS (
    SELECT id,octet_length(document::text) AS bytes
    FROM knotra_definitions
    WHERE ($2::text='' OR id<$2)
    ORDER BY id DESC
    LIMIT 101
), page AS (
    SELECT id,row_number() OVER (ORDER BY id DESC) AS position,
        COALESCE(sum(bytes) OVER (ORDER BY id DESC ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING),0) AS preceding_bytes
    FROM candidates
)
SELECT d.document
FROM knotra_definitions d JOIN page p ON p.id=d.id
WHERE p.position<=2 OR p.preceding_bytes<=$1::bigint
ORDER BY d.id DESC
`

type ListDefinitionsParams struct {
	MaxBytes int64
	Cursor   string
}

// Bound raw documents before sqlc materializes them; keep one cursor marker.
func (q *Queries) ListDefinitions(ctx context.Context, arg ListDefinitionsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listDefinitions, arg.MaxBytes, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id,document FROM knotra_events WHERE run_id=$1 AND id>$2 AND ($3::text='' OR document->>'instanceId'=$3) ORDER BY id LIMIT 100
`

type ListEventsParams struct {
	RunID      string
	ID         int64
	InstanceID string
}

type ListEventsRow struct {
	ID       int64
	Document []byte
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.RunID, arg.ID, arg.InstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(&i.ID, &i.Document); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstances = `-- name: ListInstances :many
SELECT document FROM knotra_instances WHERE run_id=$1 ORDER BY id
`

func (q *Queries) ListInstances(ctx context.Context, runID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listInstances, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT document FROM knotra_runs WHERE ($1::text='' OR id<$1) ORDER BY id DESC LIMIT 101
`

func (q *Queries) ListRuns(ctx context.Context, dollar_1 string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listRuns, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNextOutbox = `-- name: LockNextOutbox :one
SELECT o.id,o.run_id,o.kind,o.payload FROM knotra_outbox o WHERE o.sent_at IS NULL AND NOT EXISTS (SELECT 1 FROM knotra_outbox earlier WHERE earlier.run_id=o.run_id AND earlier.id<o.id AND earlier.sent_at IS NULL) ORDER BY o.id FOR UPDATE OF o SKIP LOCKED LIMIT 1
`

type LockNextOutboxRow struct {
	ID      int64
	RunID   string
	Kind    string
	Payload []byte
}

func (q *Queries) LockNextOutbox(ctx context.Context) (LockNextOutboxRow, error) {
	row := q.db.QueryRow(ctx, lockNextOutbox)
	var i LockNextOutboxRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Payload,
	)
	return i, err
}

const lockStoreSchema = `-- name: LockStoreSchema :execresult
SELECT pg_advisory_xact_lock(712865723)
`

func (q *Queries) LockStoreSchema(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, lockStoreSchema)
}

const markOutboxSent = `-- name: MarkOutboxSent :execresult
UPDATE knotra_outbox SET sent_at=now() WHERE id=$1
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, markOutboxSent, id)
}

const putDefinition = `-- name: PutDefinition :one
INSERT INTO knotra_definitions(id,digest,document) VALUES($1,$2,$3) ON CONFLICT(digest) DO UPDATE SET digest=EXCLUDED.digest RETURNING document
`

type PutDefinitionParams struct {
	ID       string
	Digest   string
	Document []byte
}

func (q *Queries) PutDefinition(ctx context.Context, arg PutDefinitionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, putDefinition, arg.ID, arg.Digest, arg.Document)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const readCommandReceipt = `-- name: ReadCommandReceipt :one
SELECT route,digest,status,response FROM knotra_commands WHERE principal=$1 AND id=$2
`

type ReadCommandReceiptParams struct {
	Principal string
	ID        string
}

type ReadCommandReceiptRow struct {
	Route    string
	Digest   string
	Status   int
	Response []byte
}

func (q *Queries) ReadCommandReceipt(ctx context.Context, arg ReadCommandReceiptParams) (ReadCommandReceiptRow, error) {
	row := q.db.QueryRow(ctx, readCommandReceipt, arg.Principal, arg.ID)
	var i ReadCommandReceiptRow
	err := row.Scan(
		&i.Route,
		&i.Digest,
		&i.Status,
		&i.Response,
	)
	return i, err
}

const readDefinition = `-- name: ReadDefinition :one
SELECT document FROM knotra_definitions WHERE id=$1
`

func (q *Queries) ReadDefinition(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, readDefinition, id)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const readEngineID = `-- name: ReadEngineID :one
SELECT value FROM knotra_settings WHERE key='engine_id'
`

func (q *Queries) ReadEngineID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, readEngineID)
	var value string
	err := row.Scan(&value)
	return value, err
}

const readPlan = `-- name: ReadPlan :one
SELECT plan FROM knotra_runs WHERE id=$1
`

func (q *Queries) ReadPlan(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, readPlan, id)
	var plan []byte
	err := row.Scan(&plan)
	return plan, err
}

const readRunBackend = `-- name: ReadRunBackend :one
SELECT backend FROM knotra_runs WHERE id=$1
`

func (q *Queries) ReadRunBackend(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, readRunBackend, id)
	var backend string
	err := row.Scan(&backend)
	return backend, err
}

const readRunInputs = `-- name: ReadRunInputs :one
SELECT inputs FROM knotra_runs WHERE id=$1
`

func (q *Queries) ReadRunInputs(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, readRunInputs, id)
	var inputs []byte
	err := row.Scan(&inputs)
	return inputs, err
}

const readRunName = `-- name: ReadRunName :one
SELECT (d.document->>'name')::text FROM knotra_runs r JOIN knotra_definitions d ON d.id=r.definition_id WHERE r.id=$1
`

func (q *Queries) ReadRunName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, readRunName, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const readRunProjection = `-- name: ReadRunProjection :one
SELECT document FROM knotra_runs WHERE id=$1
`

func (q *Queries) ReadRunProjection(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, readRunProjection, id)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const readRunStatus = `-- name: ReadRunStatus :one
SELECT (document->>'status')::text FROM knotra_runs WHERE id=$1
`

func (q *Queries) ReadRunStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, readRunStatus, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const schemaInitialized = `-- name: SchemaInitialized :one
SELECT (to_regclass('knotra_settings') IS NOT NULL)::boolean AS initialized
`

func (q *Queries) SchemaInitialized(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, schemaInitialized)
	var initialized bool
	err := row.Scan(&initialized)
	return initialized, err
}
